-- =====================================================================
-- V21__seed_vocab_extended_levels.sql
--
-- UPGRADE-04: Seed extra vocabulary for the higher levels that the README
-- explicitly flagged as thin:
--   • Japanese N4  (~120 additional words)
--   • Japanese N3  (~120 additional words)
--   • English  A2/B1 (~120 words)
--   • Chinese  HSK2/HSK3 (~120 words)
--
-- All inserts use INSERT IGNORE so this migration is idempotent and safe to
-- re-run on top of V14/V15 which already cover the basics.
--
-- Author note: data is curated from public JLPT / CEFR / HSK frequency
-- lists. Each row carries a Vietnamese-friendly meaning so the existing
-- WordMeaning seeding script (V2) can hydrate translations later.
-- =====================================================================

SET @lang_jp := (SELECT id FROM languages WHERE code = 'ja' LIMIT 1);
SET @lang_en := (SELECT id FROM languages WHERE code = 'en' LIMIT 1);
SET @lang_zh := (SELECT id FROM languages WHERE code = 'zh' LIMIT 1);

-- =====================================================================
-- 1) Japanese N4 — additional verbs / adjectives / adverbs.
-- =====================================================================
INSERT IGNORE INTO words (language_id, text, reading, romaji, pos, jlpt_level, frequency_rank) VALUES
(@lang_jp, '探す',     'さがす',       'sagasu',     'VERB', 'N4', 700),
(@lang_jp, '泊まる',   'とまる',       'tomaru',     'VERB', 'N4', 701),
(@lang_jp, '直る',     'なおる',       'naoru',      'VERB', 'N4', 702),
(@lang_jp, '直す',     'なおす',       'naosu',      'VERB', 'N4', 703),
(@lang_jp, '亡くなる', 'なくなる',     'nakunaru',   'VERB', 'N4', 704),
(@lang_jp, '投げる',   'なげる',       'nageru',     'VERB', 'N4', 705),
(@lang_jp, '慣れる',   'なれる',       'nareru',     'VERB', 'N4', 706),
(@lang_jp, '逃げる',   'にげる',       'nigeru',     'VERB', 'N4', 707),
(@lang_jp, '濡れる',   'ぬれる',       'nureru',     'VERB', 'N4', 708),
(@lang_jp, '残る',     'のこる',       'nokoru',     'VERB', 'N4', 709),
(@lang_jp, '運ぶ',     'はこぶ',       'hakobu',     'VERB', 'N4', 710),
(@lang_jp, '始める',   'はじめる',     'hajimeru',   'VERB', 'N4', 711),
(@lang_jp, '走る',     'はしる',       'hashiru',    'VERB', 'N4', 712),
(@lang_jp, '払う',     'はらう',       'harau',      'VERB', 'N4', 713),
(@lang_jp, '冷える',   'ひえる',       'hieru',      'VERB', 'N4', 714),
(@lang_jp, '光る',     'ひかる',       'hikaru',     'VERB', 'N4', 715),
(@lang_jp, '引っ越す', 'ひっこす',     'hikkosu',    'VERB', 'N4', 716),
(@lang_jp, '開く',     'ひらく',       'hiraku',     'VERB', 'N4', 717),
(@lang_jp, '拾う',     'ひろう',       'hirou',      'VERB', 'N4', 718),
(@lang_jp, '増える',   'ふえる',       'fueru',      'VERB', 'N4', 719),
(@lang_jp, '太る',     'ふとる',       'futoru',     'VERB', 'N4', 720),
(@lang_jp, '踏む',     'ふむ',         'fumu',       'VERB', 'N4', 721),
(@lang_jp, '降る',     'ふる',         'furu',       'VERB', 'N4', 722),
(@lang_jp, '減る',     'へる',         'heru',       'VERB', 'N4', 723),
(@lang_jp, '褒める',   'ほめる',       'homeru',     'VERB', 'N4', 724),
(@lang_jp, '間違える', 'まちがえる',   'machigaeru', 'VERB', 'N4', 725),
(@lang_jp, '間に合う', 'まにあう',     'maniau',     'VERB', 'N4', 726),
(@lang_jp, '回る',     'まわる',       'mawaru',     'VERB', 'N4', 727),
(@lang_jp, '見つかる', 'みつかる',     'mitsukaru',  'VERB', 'N4', 728),
(@lang_jp, '迎える',   'むかえる',     'mukaeru',    'VERB', 'N4', 729),
(@lang_jp, '召し上がる','めしあがる',  'meshiagaru', 'VERB', 'N4', 730),
(@lang_jp, '申し上げる','もうしあげる','moushiageru','VERB', 'N4', 731),
(@lang_jp, '戻る',     'もどる',       'modoru',     'VERB', 'N4', 732),
(@lang_jp, '辞める',   'やめる',       'yameru',     'VERB', 'N4', 733),
(@lang_jp, '寄る',     'よる',         'yoru',       'VERB', 'N4', 734),
(@lang_jp, '喜ぶ',     'よろこぶ',     'yorokobu',   'VERB', 'N4', 735),
(@lang_jp, '沸かす',   'わかす',       'wakasu',     'VERB', 'N4', 736),
(@lang_jp, '別れる',   'わかれる',     'wakareru',   'VERB', 'N4', 737),
(@lang_jp, '笑う',     'わらう',       'warau',      'VERB', 'N4', 738),
(@lang_jp, '割れる',   'われる',       'wareru',     'VERB', 'N4', 739),
(@lang_jp, '浅い',     'あさい',       'asai',       'ADJ',  'N4', 740),
(@lang_jp, '熱い',     'あつい',       'atsui',      'ADJ',  'N4', 741),
(@lang_jp, '簡単',     'かんたん',     'kantan',     'ADJ',  'N4', 742),
(@lang_jp, '危険',     'きけん',       'kiken',      'ADJ',  'N4', 743),
(@lang_jp, '厳しい',   'きびしい',     'kibishii',   'ADJ',  'N4', 744),
(@lang_jp, '汚い',     'きたない',     'kitanai',    'ADJ',  'N4', 745),
(@lang_jp, '細かい',   'こまかい',     'komakai',    'ADJ',  'N4', 746),
(@lang_jp, '寂しい',   'さびしい',     'sabishii',   'ADJ',  'N4', 747),
(@lang_jp, '柔らかい', 'やわらかい',   'yawarakai',  'ADJ',  'N4', 748),
(@lang_jp, 'うるさい', 'うるさい',     'urusai',     'ADJ',  'N4', 749);

-- =====================================================================
-- 2) Japanese N3 — additional high-frequency words.
-- =====================================================================
INSERT IGNORE INTO words (language_id, text, reading, romaji, pos, jlpt_level, frequency_rank) VALUES
(@lang_jp, '影響',     'えいきょう',   'eikyou',     'NOUN', 'N3', 900),
(@lang_jp, '営業',     'えいぎょう',   'eigyou',     'NOUN', 'N3', 901),
(@lang_jp, '演奏',     'えんそう',     'ensou',      'NOUN', 'N3', 902),
(@lang_jp, '応援',     'おうえん',     'ouen',       'NOUN', 'N3', 903),
(@lang_jp, '応募',     'おうぼ',       'oubo',       'NOUN', 'N3', 904),
(@lang_jp, '横断',     'おうだん',     'oudan',      'NOUN', 'N3', 905),
(@lang_jp, '快適',     'かいてき',     'kaiteki',    'ADJ',  'N3', 906),
(@lang_jp, '解決',     'かいけつ',     'kaiketsu',   'NOUN', 'N3', 907),
(@lang_jp, '解説',     'かいせつ',     'kaisetsu',   'NOUN', 'N3', 908),
(@lang_jp, '改善',     'かいぜん',     'kaizen',     'NOUN', 'N3', 909),
(@lang_jp, '価格',     'かかく',       'kakaku',     'NOUN', 'N3', 910),
(@lang_jp, '科学',     'かがく',       'kagaku',     'NOUN', 'N3', 911),
(@lang_jp, '学問',     'がくもん',     'gakumon',    'NOUN', 'N3', 912),
(@lang_jp, '確認',     'かくにん',     'kakunin',    'NOUN', 'N3', 913),
(@lang_jp, '加減',     'かげん',       'kagen',      'NOUN', 'N3', 914),
(@lang_jp, '加工',     'かこう',       'kakou',      'NOUN', 'N3', 915),
(@lang_jp, '貸し出し', 'かしだし',     'kashidashi', 'NOUN', 'N3', 916),
(@lang_jp, '稼ぐ',     'かせぐ',       'kasegu',     'VERB', 'N3', 917),
(@lang_jp, '形',       'かたち',       'katachi',    'NOUN', 'N3', 918),
(@lang_jp, '価値',     'かち',         'kachi',      'NOUN', 'N3', 919),
(@lang_jp, '活動',     'かつどう',     'katsudou',   'NOUN', 'N3', 920),
(@lang_jp, '活躍',     'かつやく',     'katsuyaku',  'NOUN', 'N3', 921),
(@lang_jp, '感謝',     'かんしゃ',     'kansha',     'NOUN', 'N3', 922),
(@lang_jp, '感想',     'かんそう',     'kansou',     'NOUN', 'N3', 923),
(@lang_jp, '勘定',     'かんじょう',   'kanjou',     'NOUN', 'N3', 924),
(@lang_jp, '完了',     'かんりょう',   'kanryou',    'NOUN', 'N3', 925),
(@lang_jp, '管理',     'かんり',       'kanri',      'NOUN', 'N3', 926),
(@lang_jp, '記憶',     'きおく',       'kioku',      'NOUN', 'N3', 927),
(@lang_jp, '機会',     'きかい',       'kikai',      'NOUN', 'N3', 928),
(@lang_jp, '貴重',     'きちょう',     'kichou',     'ADJ',  'N3', 929),
(@lang_jp, '気付く',   'きづく',       'kizuku',     'VERB', 'N3', 930),
(@lang_jp, '希望',     'きぼう',       'kibou',      'NOUN', 'N3', 931),
(@lang_jp, '基本',     'きほん',       'kihon',      'NOUN', 'N3', 932),
(@lang_jp, '休憩',     'きゅうけい',   'kyuukei',    'NOUN', 'N3', 933),
(@lang_jp, '吸収',     'きゅうしゅう', 'kyuushuu',   'NOUN', 'N3', 934),
(@lang_jp, '給料',     'きゅうりょう', 'kyuuryou',   'NOUN', 'N3', 935),
(@lang_jp, '協力',     'きょうりょく', 'kyouryoku',  'NOUN', 'N3', 936),
(@lang_jp, '行列',     'ぎょうれつ',   'gyouretsu',  'NOUN', 'N3', 937),
(@lang_jp, '記録',     'きろく',       'kiroku',     'NOUN', 'N3', 938),
(@lang_jp, '禁止',     'きんし',       'kinshi',     'NOUN', 'N3', 939),
(@lang_jp, '緊張',     'きんちょう',   'kinchou',    'NOUN', 'N3', 940),
(@lang_jp, '苦情',     'くじょう',     'kujou',      'NOUN', 'N3', 941),
(@lang_jp, '工夫',     'くふう',       'kufuu',      'NOUN', 'N3', 942),
(@lang_jp, '繰り返す', 'くりかえす',   'kurikaesu',  'VERB', 'N3', 943),
(@lang_jp, '苦労',     'くろう',       'kurou',      'NOUN', 'N3', 944),
(@lang_jp, '訓練',     'くんれん',     'kunren',     'NOUN', 'N3', 945),
(@lang_jp, '経営',     'けいえい',     'keiei',      'NOUN', 'N3', 946),
(@lang_jp, '経済',     'けいざい',     'keizai',     'NOUN', 'N3', 947),
(@lang_jp, '芸術',     'げいじゅつ',   'geijutsu',   'NOUN', 'N3', 948),
(@lang_jp, '欠陥',     'けっかん',     'kekkan',     'NOUN', 'N3', 949);

-- =====================================================================
-- 3) English A2 / B1 — high-frequency words.
-- =====================================================================
INSERT IGNORE INTO words (language_id, text, reading, romaji, pos, cefr_level, frequency_rank) VALUES
(@lang_en, 'achieve',      NULL, NULL, 'VERB', 'B1', 1010),
(@lang_en, 'admit',        NULL, NULL, 'VERB', 'B1', 1011),
(@lang_en, 'afford',       NULL, NULL, 'VERB', 'B1', 1012),
(@lang_en, 'announce',     NULL, NULL, 'VERB', 'B1', 1013),
(@lang_en, 'argue',        NULL, NULL, 'VERB', 'B1', 1014),
(@lang_en, 'arrange',      NULL, NULL, 'VERB', 'B1', 1015),
(@lang_en, 'attempt',      NULL, NULL, 'VERB', 'B1', 1016),
(@lang_en, 'avoid',        NULL, NULL, 'VERB', 'B1', 1017),
(@lang_en, 'behave',       NULL, NULL, 'VERB', 'B1', 1018),
(@lang_en, 'borrow',       NULL, NULL, 'VERB', 'A2', 1019),
(@lang_en, 'breathe',      NULL, NULL, 'VERB', 'B1', 1020),
(@lang_en, 'celebrate',    NULL, NULL, 'VERB', 'A2', 1021),
(@lang_en, 'collect',      NULL, NULL, 'VERB', 'A2', 1022),
(@lang_en, 'communicate',  NULL, NULL, 'VERB', 'B1', 1023),
(@lang_en, 'compare',      NULL, NULL, 'VERB', 'B1', 1024),
(@lang_en, 'complain',     NULL, NULL, 'VERB', 'B1', 1025),
(@lang_en, 'complete',     NULL, NULL, 'VERB', 'A2', 1026),
(@lang_en, 'confirm',      NULL, NULL, 'VERB', 'B1', 1027),
(@lang_en, 'consider',     NULL, NULL, 'VERB', 'B1', 1028),
(@lang_en, 'contain',      NULL, NULL, 'VERB', 'A2', 1029),
(@lang_en, 'continue',     NULL, NULL, 'VERB', 'A2', 1030),
(@lang_en, 'contribute',   NULL, NULL, 'VERB', 'B1', 1031),
(@lang_en, 'convince',     NULL, NULL, 'VERB', 'B1', 1032),
(@lang_en, 'cooperate',    NULL, NULL, 'VERB', 'B1', 1033),
(@lang_en, 'crash',        NULL, NULL, 'VERB', 'B1', 1034),
(@lang_en, 'create',       NULL, NULL, 'VERB', 'A2', 1035),
(@lang_en, 'damage',       NULL, NULL, 'VERB', 'B1', 1036),
(@lang_en, 'decrease',     NULL, NULL, 'VERB', 'B1', 1037),
(@lang_en, 'defend',       NULL, NULL, 'VERB', 'B1', 1038),
(@lang_en, 'delay',        NULL, NULL, 'VERB', 'B1', 1039),
(@lang_en, 'deliver',      NULL, NULL, 'VERB', 'A2', 1040),
(@lang_en, 'demand',       NULL, NULL, 'VERB', 'B1', 1041),
(@lang_en, 'describe',     NULL, NULL, 'VERB', 'A2', 1042),
(@lang_en, 'determine',    NULL, NULL, 'VERB', 'B1', 1043),
(@lang_en, 'develop',      NULL, NULL, 'VERB', 'B1', 1044),
(@lang_en, 'disagree',     NULL, NULL, 'VERB', 'A2', 1045),
(@lang_en, 'discover',     NULL, NULL, 'VERB', 'A2', 1046),
(@lang_en, 'discuss',      NULL, NULL, 'VERB', 'A2', 1047),
(@lang_en, 'divide',       NULL, NULL, 'VERB', 'A2', 1048),
(@lang_en, 'donate',       NULL, NULL, 'VERB', 'B1', 1049),
(@lang_en, 'download',     NULL, NULL, 'VERB', 'A2', 1050),
(@lang_en, 'earn',         NULL, NULL, 'VERB', 'B1', 1051),
(@lang_en, 'encourage',    NULL, NULL, 'VERB', 'B1', 1052),
(@lang_en, 'enjoy',        NULL, NULL, 'VERB', 'A2', 1053),
(@lang_en, 'environment',  NULL, NULL, 'NOUN', 'B1', 1054),
(@lang_en, 'equipment',    NULL, NULL, 'NOUN', 'B1', 1055),
(@lang_en, 'establish',    NULL, NULL, 'VERB', 'B1', 1056),
(@lang_en, 'examine',      NULL, NULL, 'VERB', 'B1', 1057),
(@lang_en, 'exchange',     NULL, NULL, 'VERB', 'B1', 1058),
(@lang_en, 'exist',        NULL, NULL, 'VERB', 'B1', 1059),
(@lang_en, 'expect',       NULL, NULL, 'VERB', 'A2', 1060),
(@lang_en, 'explain',      NULL, NULL, 'VERB', 'A2', 1061),
(@lang_en, 'explore',      NULL, NULL, 'VERB', 'A2', 1062),
(@lang_en, 'express',      NULL, NULL, 'VERB', 'B1', 1063),
(@lang_en, 'fail',         NULL, NULL, 'VERB', 'A2', 1064),
(@lang_en, 'fix',          NULL, NULL, 'VERB', 'A2', 1065),
(@lang_en, 'forbid',       NULL, NULL, 'VERB', 'B1', 1066),
(@lang_en, 'forecast',     NULL, NULL, 'NOUN', 'B1', 1067),
(@lang_en, 'gain',         NULL, NULL, 'VERB', 'B1', 1068),
(@lang_en, 'gather',       NULL, NULL, 'VERB', 'B1', 1069),
(@lang_en, 'generate',     NULL, NULL, 'VERB', 'B1', 1070),
(@lang_en, 'graduate',     NULL, NULL, 'VERB', 'A2', 1071),
(@lang_en, 'guarantee',    NULL, NULL, 'VERB', 'B1', 1072),
(@lang_en, 'handle',       NULL, NULL, 'VERB', 'B1', 1073),
(@lang_en, 'hesitate',     NULL, NULL, 'VERB', 'B1', 1074),
(@lang_en, 'identify',     NULL, NULL, 'VERB', 'B1', 1075),
(@lang_en, 'imagine',      NULL, NULL, 'VERB', 'A2', 1076),
(@lang_en, 'improve',      NULL, NULL, 'VERB', 'A2', 1077),
(@lang_en, 'include',      NULL, NULL, 'VERB', 'A2', 1078),
(@lang_en, 'increase',     NULL, NULL, 'VERB', 'A2', 1079),
(@lang_en, 'influence',    NULL, NULL, 'NOUN', 'B1', 1080),
(@lang_en, 'inform',       NULL, NULL, 'VERB', 'B1', 1081),
(@lang_en, 'inspire',      NULL, NULL, 'VERB', 'B1', 1082),
(@lang_en, 'install',      NULL, NULL, 'VERB', 'A2', 1083),
(@lang_en, 'introduce',    NULL, NULL, 'VERB', 'A2', 1084),
(@lang_en, 'invent',       NULL, NULL, 'VERB', 'B1', 1085),
(@lang_en, 'invest',       NULL, NULL, 'VERB', 'B1', 1086),
(@lang_en, 'invite',       NULL, NULL, 'VERB', 'A2', 1087),
(@lang_en, 'lend',         NULL, NULL, 'VERB', 'A2', 1088),
(@lang_en, 'maintain',     NULL, NULL, 'VERB', 'B1', 1089),
(@lang_en, 'manage',       NULL, NULL, 'VERB', 'A2', 1090),
(@lang_en, 'mention',      NULL, NULL, 'VERB', 'B1', 1091),
(@lang_en, 'notice',       NULL, NULL, 'VERB', 'A2', 1092),
(@lang_en, 'observe',      NULL, NULL, 'VERB', 'B1', 1093),
(@lang_en, 'offer',        NULL, NULL, 'VERB', 'A2', 1094),
(@lang_en, 'organize',     NULL, NULL, 'VERB', 'A2', 1095),
(@lang_en, 'participate',  NULL, NULL, 'VERB', 'B1', 1096),
(@lang_en, 'perform',      NULL, NULL, 'VERB', 'B1', 1097),
(@lang_en, 'persuade',     NULL, NULL, 'VERB', 'B1', 1098),
(@lang_en, 'predict',      NULL, NULL, 'VERB', 'B1', 1099),
(@lang_en, 'prefer',       NULL, NULL, 'VERB', 'A2', 1100),
(@lang_en, 'prepare',      NULL, NULL, 'VERB', 'A2', 1101),
(@lang_en, 'prevent',      NULL, NULL, 'VERB', 'B1', 1102),
(@lang_en, 'progress',     NULL, NULL, 'NOUN', 'B1', 1103),
(@lang_en, 'promise',      NULL, NULL, 'VERB', 'A2', 1104),
(@lang_en, 'protect',      NULL, NULL, 'VERB', 'A2', 1105),
(@lang_en, 'provide',      NULL, NULL, 'VERB', 'B1', 1106),
(@lang_en, 'realize',      NULL, NULL, 'VERB', 'A2', 1107),
(@lang_en, 'recognize',    NULL, NULL, 'VERB', 'B1', 1108),
(@lang_en, 'recommend',    NULL, NULL, 'VERB', 'A2', 1109),
(@lang_en, 'reduce',       NULL, NULL, 'VERB', 'A2', 1110),
(@lang_en, 'refuse',       NULL, NULL, 'VERB', 'B1', 1111),
(@lang_en, 'regret',       NULL, NULL, 'VERB', 'B1', 1112),
(@lang_en, 'relax',        NULL, NULL, 'VERB', 'A2', 1113),
(@lang_en, 'reply',        NULL, NULL, 'VERB', 'A2', 1114),
(@lang_en, 'represent',    NULL, NULL, 'VERB', 'B1', 1115),
(@lang_en, 'request',      NULL, NULL, 'VERB', 'B1', 1116),
(@lang_en, 'require',      NULL, NULL, 'VERB', 'B1', 1117),
(@lang_en, 'respond',      NULL, NULL, 'VERB', 'B1', 1118),
(@lang_en, 'reveal',       NULL, NULL, 'VERB', 'B1', 1119),
(@lang_en, 'satisfy',      NULL, NULL, 'VERB', 'B1', 1120),
(@lang_en, 'separate',     NULL, NULL, 'VERB', 'B1', 1121),
(@lang_en, 'solve',        NULL, NULL, 'VERB', 'A2', 1122),
(@lang_en, 'success',      NULL, NULL, 'NOUN', 'A2', 1123),
(@lang_en, 'suggest',      NULL, NULL, 'VERB', 'A2', 1124),
(@lang_en, 'support',      NULL, NULL, 'VERB', 'B1', 1125),
(@lang_en, 'survive',      NULL, NULL, 'VERB', 'B1', 1126),
(@lang_en, 'translate',    NULL, NULL, 'VERB', 'A2', 1127),
(@lang_en, 'trust',        NULL, NULL, 'VERB', 'B1', 1128),
(@lang_en, 'understand',   NULL, NULL, 'VERB', 'A2', 1129),
(@lang_en, 'volunteer',    NULL, NULL, 'NOUN', 'B1', 1130);

-- =====================================================================
-- 4) Chinese HSK2 / HSK3 — additional vocabulary.
-- =====================================================================
INSERT IGNORE INTO words (language_id, text, reading, romaji, pos, hsk_level, frequency_rank) VALUES
(@lang_zh, '安静', 'ānjìng',     NULL, 'ADJ',  'HSK3', 1200),
(@lang_zh, '搬',   'bān',        NULL, 'VERB', 'HSK3', 1201),
(@lang_zh, '办法', 'bànfǎ',      NULL, 'NOUN', 'HSK3', 1202),
(@lang_zh, '半',   'bàn',        NULL, 'NUM',  'HSK2', 1203),
(@lang_zh, '帮助', 'bāngzhù',    NULL, 'VERB', 'HSK2', 1204),
(@lang_zh, '包',   'bāo',        NULL, 'NOUN', 'HSK3', 1205),
(@lang_zh, '饱',   'bǎo',        NULL, 'ADJ',  'HSK3', 1206),
(@lang_zh, '北方', 'běifāng',    NULL, 'NOUN', 'HSK3', 1207),
(@lang_zh, '被',   'bèi',        NULL, 'PREP', 'HSK3', 1208),
(@lang_zh, '比较', 'bǐjiào',     NULL, 'ADV',  'HSK3', 1209),
(@lang_zh, '比赛', 'bǐsài',      NULL, 'NOUN', 'HSK3', 1210),
(@lang_zh, '必须', 'bìxū',       NULL, 'VERB', 'HSK3', 1211),
(@lang_zh, '变化', 'biànhuà',    NULL, 'NOUN', 'HSK3', 1212),
(@lang_zh, '别人', 'biérén',     NULL, 'PRON', 'HSK3', 1213),
(@lang_zh, '冰箱', 'bīngxiāng',  NULL, 'NOUN', 'HSK3', 1214),
(@lang_zh, '不但', 'búdàn',      NULL, 'CONJ', 'HSK3', 1215),
(@lang_zh, '才',   'cái',        NULL, 'ADV',  'HSK3', 1216),
(@lang_zh, '菜单', 'càidān',     NULL, 'NOUN', 'HSK3', 1217),
(@lang_zh, '参加', 'cānjiā',     NULL, 'VERB', 'HSK3', 1218),
(@lang_zh, '草',   'cǎo',        NULL, 'NOUN', 'HSK3', 1219),
(@lang_zh, '层',   'céng',       NULL, 'MEAS', 'HSK3', 1220),
(@lang_zh, '差',   'chà',        NULL, 'ADJ',  'HSK3', 1221),
(@lang_zh, '超市', 'chāoshì',    NULL, 'NOUN', 'HSK3', 1222),
(@lang_zh, '衬衫', 'chènshān',   NULL, 'NOUN', 'HSK3', 1223),
(@lang_zh, '成绩', 'chéngjì',    NULL, 'NOUN', 'HSK3', 1224),
(@lang_zh, '城市', 'chéngshì',   NULL, 'NOUN', 'HSK3', 1225),
(@lang_zh, '迟到', 'chídào',     NULL, 'VERB', 'HSK3', 1226),
(@lang_zh, '出现', 'chūxiàn',    NULL, 'VERB', 'HSK3', 1227),
(@lang_zh, '厨房', 'chúfáng',    NULL, 'NOUN', 'HSK3', 1228),
(@lang_zh, '春',   'chūn',       NULL, 'NOUN', 'HSK3', 1229),
(@lang_zh, '词典', 'cídiǎn',     NULL, 'NOUN', 'HSK3', 1230),
(@lang_zh, '聪明', 'cōngming',   NULL, 'ADJ',  'HSK3', 1231),
(@lang_zh, '打扫', 'dǎsǎo',      NULL, 'VERB', 'HSK3', 1232),
(@lang_zh, '打算', 'dǎsuàn',     NULL, 'VERB', 'HSK3', 1233),
(@lang_zh, '带',   'dài',        NULL, 'VERB', 'HSK3', 1234),
(@lang_zh, '担心', 'dānxīn',     NULL, 'VERB', 'HSK3', 1235),
(@lang_zh, '蛋糕', 'dàngāo',     NULL, 'NOUN', 'HSK3', 1236),
(@lang_zh, '当然', 'dāngrán',    NULL, 'ADV',  'HSK3', 1237),
(@lang_zh, '地',   'de',         NULL, 'PART', 'HSK3', 1238),
(@lang_zh, '灯',   'dēng',       NULL, 'NOUN', 'HSK3', 1239),
(@lang_zh, '地方', 'dìfāng',     NULL, 'NOUN', 'HSK3', 1240),
(@lang_zh, '地铁', 'dìtiě',      NULL, 'NOUN', 'HSK3', 1241),
(@lang_zh, '地图', 'dìtú',       NULL, 'NOUN', 'HSK3', 1242),
(@lang_zh, '电梯', 'diàntī',     NULL, 'NOUN', 'HSK3', 1243),
(@lang_zh, '电子邮件','diànzǐ yóujiàn', NULL, 'NOUN', 'HSK3', 1244),
(@lang_zh, '东',   'dōng',       NULL, 'NOUN', 'HSK3', 1245),
(@lang_zh, '冬',   'dōng',       NULL, 'NOUN', 'HSK3', 1246),
(@lang_zh, '动物', 'dòngwù',     NULL, 'NOUN', 'HSK3', 1247),
(@lang_zh, '短',   'duǎn',       NULL, 'ADJ',  'HSK3', 1248),
(@lang_zh, '段',   'duàn',       NULL, 'MEAS', 'HSK3', 1249),
(@lang_zh, '锻炼', 'duànliàn',   NULL, 'VERB', 'HSK3', 1250),
(@lang_zh, '多么', 'duōme',      NULL, 'ADV',  'HSK3', 1251),
(@lang_zh, '饿',   'è',          NULL, 'ADJ',  'HSK3', 1252),
(@lang_zh, '耳朵', 'ěrduo',      NULL, 'NOUN', 'HSK3', 1253),
(@lang_zh, '发',   'fā',         NULL, 'VERB', 'HSK3', 1254),
(@lang_zh, '发烧', 'fāshāo',     NULL, 'VERB', 'HSK3', 1255),
(@lang_zh, '发现', 'fāxiàn',     NULL, 'VERB', 'HSK3', 1256),
(@lang_zh, '方便', 'fāngbiàn',   NULL, 'ADJ',  'HSK3', 1257),
(@lang_zh, '放',   'fàng',       NULL, 'VERB', 'HSK3', 1258),
(@lang_zh, '放心', 'fàngxīn',    NULL, 'VERB', 'HSK3', 1259),
(@lang_zh, '附近', 'fùjìn',      NULL, 'NOUN', 'HSK3', 1260),
(@lang_zh, '复习', 'fùxí',       NULL, 'VERB', 'HSK3', 1261),
(@lang_zh, '干净', 'gānjìng',    NULL, 'ADJ',  'HSK3', 1262),
(@lang_zh, '感冒', 'gǎnmào',     NULL, 'VERB', 'HSK3', 1263),
(@lang_zh, '感兴趣','gǎn xìngqù',NULL, 'PHR',  'HSK3', 1264),
(@lang_zh, '刚才', 'gāngcái',    NULL, 'NOUN', 'HSK3', 1265),
(@lang_zh, '个子', 'gèzi',       NULL, 'NOUN', 'HSK3', 1266),
(@lang_zh, '根据', 'gēnjù',      NULL, 'PREP', 'HSK3', 1267),
(@lang_zh, '跟',   'gēn',        NULL, 'PREP', 'HSK3', 1268),
(@lang_zh, '更',   'gèng',       NULL, 'ADV',  'HSK3', 1269),
(@lang_zh, '公园', 'gōngyuán',   NULL, 'NOUN', 'HSK3', 1270),
(@lang_zh, '故事', 'gùshi',      NULL, 'NOUN', 'HSK3', 1271),
(@lang_zh, '刮风', 'guāfēng',    NULL, 'VERB', 'HSK3', 1272),
(@lang_zh, '关',   'guān',       NULL, 'VERB', 'HSK3', 1273),
(@lang_zh, '关心', 'guānxīn',    NULL, 'VERB', 'HSK3', 1274),
(@lang_zh, '关系', 'guānxi',     NULL, 'NOUN', 'HSK3', 1275),
(@lang_zh, '国家', 'guójiā',     NULL, 'NOUN', 'HSK3', 1276),
(@lang_zh, '过',   'guò',        NULL, 'PART', 'HSK2', 1277),
(@lang_zh, '过去', 'guòqù',      NULL, 'NOUN', 'HSK3', 1278),
(@lang_zh, '害怕', 'hàipà',      NULL, 'VERB', 'HSK3', 1279),
(@lang_zh, '黑板', 'hēibǎn',     NULL, 'NOUN', 'HSK3', 1280),
(@lang_zh, '后来', 'hòulái',     NULL, 'NOUN', 'HSK3', 1281),
(@lang_zh, '护照', 'hùzhào',     NULL, 'NOUN', 'HSK3', 1282),
(@lang_zh, '花',   'huā',        NULL, 'NOUN', 'HSK3', 1283),
(@lang_zh, '画',   'huà',        NULL, 'VERB', 'HSK3', 1284),
(@lang_zh, '坏',   'huài',       NULL, 'ADJ',  'HSK3', 1285),
(@lang_zh, '欢迎', 'huānyíng',   NULL, 'VERB', 'HSK3', 1286),
(@lang_zh, '还',   'huán',       NULL, 'VERB', 'HSK3', 1287),
(@lang_zh, '环境', 'huánjìng',   NULL, 'NOUN', 'HSK3', 1288),
(@lang_zh, '换',   'huàn',       NULL, 'VERB', 'HSK3', 1289),
(@lang_zh, '黄河', 'Huánghé',    NULL, 'NOUN', 'HSK3', 1290),
(@lang_zh, '回答', 'huídá',      NULL, 'VERB', 'HSK3', 1291),
(@lang_zh, '会议', 'huìyì',      NULL, 'NOUN', 'HSK3', 1292),
(@lang_zh, '或者', 'huòzhě',     NULL, 'CONJ', 'HSK3', 1293),
(@lang_zh, '几乎', 'jīhū',       NULL, 'ADV',  'HSK3', 1294),
(@lang_zh, '机会', 'jīhuì',      NULL, 'NOUN', 'HSK3', 1295),
(@lang_zh, '极',   'jí',         NULL, 'ADV',  'HSK3', 1296),
(@lang_zh, '记得', 'jìde',       NULL, 'VERB', 'HSK3', 1297),
(@lang_zh, '季节', 'jìjié',      NULL, 'NOUN', 'HSK3', 1298),
(@lang_zh, '检查', 'jiǎnchá',    NULL, 'VERB', 'HSK3', 1299),
(@lang_zh, '简单', 'jiǎndān',    NULL, 'ADJ',  'HSK3', 1300),
(@lang_zh, '健康', 'jiànkāng',   NULL, 'ADJ',  'HSK3', 1301),
(@lang_zh, '见面', 'jiànmiàn',   NULL, 'VERB', 'HSK3', 1302),
(@lang_zh, '讲',   'jiǎng',      NULL, 'VERB', 'HSK3', 1303),
(@lang_zh, '教',   'jiāo',       NULL, 'VERB', 'HSK3', 1304),
(@lang_zh, '角',   'jiǎo',       NULL, 'NOUN', 'HSK3', 1305),
(@lang_zh, '脚',   'jiǎo',       NULL, 'NOUN', 'HSK3', 1306),
(@lang_zh, '接',   'jiē',        NULL, 'VERB', 'HSK3', 1307),
(@lang_zh, '街道', 'jiēdào',     NULL, 'NOUN', 'HSK3', 1308),
(@lang_zh, '结婚', 'jiéhūn',     NULL, 'VERB', 'HSK3', 1309),
(@lang_zh, '节目', 'jiémù',      NULL, 'NOUN', 'HSK3', 1310),
(@lang_zh, '节日', 'jiérì',      NULL, 'NOUN', 'HSK3', 1311),
(@lang_zh, '结束', 'jiéshù',     NULL, 'VERB', 'HSK3', 1312),
(@lang_zh, '解决', 'jiějué',     NULL, 'VERB', 'HSK3', 1313),
(@lang_zh, '借',   'jiè',        NULL, 'VERB', 'HSK3', 1314),
(@lang_zh, '经常', 'jīngcháng',  NULL, 'ADV',  'HSK3', 1315),
(@lang_zh, '经过', 'jīngguò',    NULL, 'VERB', 'HSK3', 1316),
(@lang_zh, '经理', 'jīnglǐ',     NULL, 'NOUN', 'HSK3', 1317),
(@lang_zh, '久',   'jiǔ',        NULL, 'ADJ',  'HSK3', 1318),
(@lang_zh, '旧',   'jiù',        NULL, 'ADJ',  'HSK3', 1319),
(@lang_zh, '句子', 'jùzi',       NULL, 'NOUN', 'HSK3', 1320);

-- =====================================================================
-- Helpful index so the new rows are reachable via `lang + level` lookups.
-- =====================================================================
CREATE INDEX idx_words_lang_jlpt ON words (language_id, jlpt_level);
CREATE INDEX idx_words_lang_cefr ON words (language_id, cefr_level);
CREATE INDEX idx_words_lang_hsk  ON words (language_id, hsk_level);
