-- =====================================================
-- LINGUA PLATFORM - Seed Data V5
-- KANJI JLPT N5 (~80 chars) + N4 (~50 chars) extended
-- Hanzi HSK (Chinese characters)
-- Grammar 3 languages (60+ patterns)
-- =====================================================

-- ========================
-- KANJI JLPT N5 (Extended set - 80+ kanji)
-- language_id = 1 (Japanese)
-- ========================
INSERT INTO characters_table (id, language_id, character_text, stroke_count, jlpt_level, frequency_rank, meaning_vi, meaning_en, on_reading, kun_reading, han_viet, mnemonic_text) VALUES
-- Numbers
(100, 1, '一', 1, 'N5', 1, 'Một', 'One', 'イチ、イツ', 'ひと(つ)', 'Nhất', 'Một nét ngang đơn giản = số 1.'),
(101, 1, '二', 2, 'N5', 2, 'Hai', 'Two', 'ニ', 'ふた(つ)', 'Nhị', 'Hai nét ngang chồng lên nhau = số 2.'),
(102, 1, '三', 3, 'N5', 3, 'Ba', 'Three', 'サン', 'み(つ)', 'Tam', 'Ba nét ngang xếp chồng = số 3.'),
(103, 1, '四', 5, 'N5', 4, 'Bốn', 'Four', 'シ', 'よ、よ(つ)、よん', 'Tứ', 'Hình hộp với 2 chân, có 4 góc = số 4.'),
(104, 1, '五', 4, 'N5', 5, 'Năm', 'Five', 'ゴ', 'いつ(つ)', 'Ngũ', 'Hình chữ Z với nét ngang = số 5.'),
(105, 1, '六', 4, 'N5', 6, 'Sáu', 'Six', 'ロク', 'む、む(つ)', 'Lục', 'Mái nhà với 2 chân = số 6.'),
(106, 1, '七', 2, 'N5', 7, 'Bảy', 'Seven', 'シチ', 'なな、なな(つ)', 'Thất', 'Lưỡi liềm cong = số 7.'),
(107, 1, '八', 2, 'N5', 8, 'Tám', 'Eight', 'ハチ', 'や、や(つ)', 'Bát', 'Hai nét xòe ra như cánh chim = số 8.'),
(108, 1, '九', 2, 'N5', 9, 'Chín', 'Nine', 'キュウ、ク', 'ここの(つ)', 'Cửu', 'Giống số 9 viết tay.'),
(109, 1, '十', 2, 'N5', 10, 'Mười', 'Ten', 'ジュウ', 'とお、と', 'Thập', 'Dấu cộng = số 10 trong chữ Hán.'),
(110, 1, '百', 6, 'N5', 11, 'Trăm', 'Hundred', 'ヒャク', NULL, 'Bách', 'Một (一) trên trăm (白) = một trăm.'),
(111, 1, '千', 3, 'N5', 12, 'Nghìn', 'Thousand', 'セン', 'ち', 'Thiên', 'Người (人) bị giẫm = nghìn.'),
(112, 1, '万', 3, 'N5', 13, 'Vạn', 'Ten thousand', 'マン、バン', NULL, 'Vạn', 'Hình người trải rộng tay = nhiều, vạn.'),
-- People & Family
(113, 1, '人', 2, 'N5', 14, 'Người', 'Person', 'ジン、ニン', 'ひと', 'Nhân', 'Hình người đứng dang chân.'),
(114, 1, '男', 7, 'N5', 15, 'Nam (đàn ông)', 'Man, male', 'ダン、ナン', 'おとこ', 'Nam', 'Ruộng (田) + sức (力) = đàn ông làm ruộng.'),
(115, 1, '女', 3, 'N5', 16, 'Nữ', 'Woman, female', 'ジョ、ニョ', 'おんな、め', 'Nữ', 'Hình phụ nữ ngồi quỳ duỗi tay.'),
(116, 1, '子', 3, 'N5', 17, 'Con', 'Child', 'シ、ス', 'こ', 'Tử', 'Hình em bé quấn tã.'),
(117, 1, '父', 4, 'N5', 18, 'Cha', 'Father', 'フ', 'ちち', 'Phụ', 'Hình người đàn ông cầm rìu.'),
(118, 1, '母', 5, 'N5', 19, 'Mẹ', 'Mother', 'ボ', 'はは', 'Mẫu', 'Hình ngực mẹ đang cho con bú.'),
(119, 1, '友', 4, 'N5', 20, 'Bạn', 'Friend', 'ユウ', 'とも', 'Hữu', 'Hai bàn tay (又) đan vào nhau = bạn bè.'),
-- Nature
(120, 1, '日', 4, 'N5', 21, 'Ngày, mặt trời', 'Day, sun', 'ニチ、ジツ', 'ひ、び、か', 'Nhật', 'Hình tròn của mặt trời với chấm bên trong.'),
(121, 1, '月', 4, 'N5', 22, 'Tháng, mặt trăng', 'Month, moon', 'ゲツ、ガツ', 'つき', 'Nguyệt', 'Hình lưỡi liềm của trăng khuyết.'),
(122, 1, '火', 4, 'N5', 23, 'Lửa', 'Fire', 'カ', 'ひ', 'Hỏa', 'Hình ngọn lửa đang cháy.'),
(123, 1, '水', 4, 'N5', 24, 'Nước', 'Water', 'スイ', 'みず', 'Thủy', 'Hình dòng nước chảy.'),
(124, 1, '木', 4, 'N5', 25, 'Cây, gỗ', 'Tree, wood', 'モク、ボク', 'き、こ', 'Mộc', 'Hình cây với cành lá vươn ra.'),
(125, 1, '金', 8, 'N5', 26, 'Vàng, kim loại, tiền', 'Gold, metal, money', 'キン、コン', 'かね、かな', 'Kim', 'Mái nhà che vàng dưới đất = kim loại quý.'),
(126, 1, '土', 3, 'N5', 27, 'Đất', 'Earth, ground', 'ド、ト', 'つち', 'Thổ', 'Cây mọc từ đất = mặt đất.'),
(127, 1, '山', 3, 'N5', 28, 'Núi', 'Mountain', 'サン', 'やま', 'Sơn', 'Ba đỉnh núi nhọn.'),
(128, 1, '川', 3, 'N5', 29, 'Sông', 'River', 'セン', 'かわ', 'Xuyên', 'Ba dòng nước chảy song song.'),
(129, 1, '田', 5, 'N5', 30, 'Ruộng', 'Rice field', 'デン', 'た、だ', 'Điền', 'Ô vuông chia làm 4 ô nhỏ = ruộng lúa.'),
(130, 1, '雨', 8, 'N5', 31, 'Mưa', 'Rain', 'ウ', 'あめ', 'Vũ', 'Mây trên trời thả những giọt nước.'),
(131, 1, '空', 8, 'N5', 32, 'Bầu trời, không', 'Sky, empty', 'クウ', 'そら、あ(く)', 'Không', 'Hang động (穴) + công (工) = trống không.'),
(132, 1, '気', 6, 'N5', 33, 'Khí, tinh thần', 'Spirit, energy', 'キ、ケ', NULL, 'Khí', 'Hơi nước bốc lên từ gạo = khí.'),
(133, 1, '花', 7, 'N5', 34, 'Hoa', 'Flower', 'カ', 'はな', 'Hoa', 'Cỏ (艹) + hóa (化) = hoa nở.'),
(134, 1, '魚', 11, 'N5', 35, 'Cá', 'Fish', 'ギョ', 'うお、さかな', 'Ngư', 'Hình con cá có đầu thân đuôi.'),
(135, 1, '犬', 4, 'N5', 36, 'Chó', 'Dog', 'ケン', 'いぬ', 'Khuyển', 'Đại (大) + chấm = con chó vẫy đuôi.'),
-- Body parts
(136, 1, '目', 5, 'N5', 37, 'Mắt', 'Eye', 'モク', 'め', 'Mục', 'Hình con mắt với 2 mí và đồng tử.'),
(137, 1, '耳', 6, 'N5', 38, 'Tai', 'Ear', 'ジ', 'みみ', 'Nhĩ', 'Hình cái tai có vành.'),
(138, 1, '口', 3, 'N5', 39, 'Miệng', 'Mouth', 'コウ、ク', 'くち', 'Khẩu', 'Hình miệng đang mở.'),
(139, 1, '手', 4, 'N5', 40, 'Tay', 'Hand', 'シュ', 'て', 'Thủ', 'Hình bàn tay với 5 ngón.'),
(140, 1, '足', 7, 'N5', 41, 'Chân', 'Foot, leg', 'ソク', 'あし、た(りる)', 'Túc', 'Đầu gối + bàn chân.'),
-- Position
(141, 1, '上', 3, 'N5', 42, 'Trên', 'Above, up', 'ジョウ、ショウ', 'うえ、あ(げる)、のぼ(る)', 'Thượng', 'Một nét trên đường ngang = phía trên.'),
(142, 1, '下', 3, 'N5', 43, 'Dưới', 'Below, down', 'カ、ゲ', 'した、しも、さ(げる)', 'Hạ', 'Một nét dưới đường ngang = phía dưới.'),
(143, 1, '中', 4, 'N5', 44, 'Giữa, trong', 'Middle, inside', 'チュウ', 'なか', 'Trung', 'Mũi tên xuyên qua ô vuông = ở giữa.'),
(144, 1, '左', 5, 'N5', 45, 'Trái', 'Left', 'サ', 'ひだり', 'Tả', 'Tay trái cầm dụng cụ thợ.'),
(145, 1, '右', 5, 'N5', 46, 'Phải', 'Right', 'ウ、ユウ', 'みぎ', 'Hữu', 'Tay phải cầm vật dùng để ăn.'),
(146, 1, '前', 9, 'N5', 47, 'Trước', 'Front, before', 'ゼン', 'まえ', 'Tiền', 'Đứng trước = phía trước.'),
(147, 1, '後', 9, 'N5', 48, 'Sau', 'After, behind', 'ゴ、コウ', 'うし(ろ)、あと、のち', 'Hậu', 'Đi chậm phía sau = sau.'),
(148, 1, '外', 5, 'N5', 49, 'Ngoài', 'Outside', 'ガイ、ゲ', 'そと、ほか', 'Ngoại', 'Buổi tối (夕) + bói toán (卜) = ra ngoài.'),
(149, 1, '東', 8, 'N5', 50, 'Đông', 'East', 'トウ', 'ひがし', 'Đông', 'Mặt trời (日) sau cây (木) = phía đông.'),
(150, 1, '西', 6, 'N5', 51, 'Tây', 'West', 'セイ、サイ', 'にし', 'Tây', 'Hình tổ chim - chim về tổ khi mặt trời lặn về tây.'),
(151, 1, '北', 5, 'N5', 52, 'Bắc', 'North', 'ホク', 'きた', 'Bắc', 'Hai người quay lưng vào nhau (lạnh phía bắc).'),
(152, 1, '南', 9, 'N5', 53, 'Nam', 'South', 'ナン、ナ', 'みなみ', 'Nam', 'Hướng có cây cối phong phú = phía nam.'),
-- Common verbs/concepts
(153, 1, '行', 6, 'N5', 54, 'Đi', 'Go', 'コウ、ギョウ', 'い(く)、おこな(う)', 'Hành', 'Hình ngã tư = đi đến đâu.'),
(154, 1, '来', 7, 'N5', 55, 'Đến', 'Come', 'ライ', 'く(る)、きた(る)', 'Lai', 'Hình lúa chín = đến mùa thu hoạch.'),
(155, 1, '見', 7, 'N5', 56, 'Nhìn', 'See, look', 'ケン', 'み(る)', 'Kiến', 'Mắt (目) + chân (儿) = đi và nhìn.'),
(156, 1, '聞', 14, 'N5', 57, 'Nghe', 'Hear', 'ブン、モン', 'き(く)', 'Văn', 'Tai (耳) trong cổng (門) = lắng nghe.'),
(157, 1, '読', 14, 'N5', 58, 'Đọc', 'Read', 'ドク、トク', 'よ(む)', 'Độc', 'Lời nói (言) + bán (売) = đọc to.'),
(158, 1, '書', 10, 'N5', 59, 'Viết, sách', 'Write, book', 'ショ', 'か(く)', 'Thư', 'Bút (聿) viết trên giấy = viết.'),
(159, 1, '話', 13, 'N5', 60, 'Nói chuyện', 'Talk, speak', 'ワ', 'はなし、はな(す)', 'Thoại', 'Lời nói (言) + lưỡi (舌) = trò chuyện.'),
(160, 1, '言', 7, 'N5', 61, 'Nói', 'Say', 'ゲン、ゴン', 'い(う)、こと', 'Ngôn', 'Miệng phát ra âm thanh = lời nói.'),
(161, 1, '食', 9, 'N5', 62, 'Ăn', 'Eat', 'ショク', 'た(べる)、く(う)', 'Thực', 'Bát cơm có nắp = đồ ăn.'),
(162, 1, '飲', 12, 'N5', 63, 'Uống', 'Drink', 'イン', 'の(む)', 'Ẩm', 'Đồ ăn (食) + thiếu (欠) = uống.'),
(163, 1, '買', 12, 'N5', 64, 'Mua', 'Buy', 'バイ', 'か(う)', 'Mãi', 'Lưới (网) + tiền (貝) = bắt được mua.'),
(164, 1, '出', 5, 'N5', 65, 'Ra', 'Go out, exit', 'シュツ、スイ', 'で(る)、だ(す)', 'Xuất', 'Cây mọc từ đất = đi ra.'),
(165, 1, '入', 2, 'N5', 66, 'Vào', 'Enter', 'ニュウ', 'はい(る)、い(る)、い(れる)', 'Nhập', 'Mũi tên xuống = đi vào trong.'),
(166, 1, '立', 5, 'N5', 67, 'Đứng', 'Stand', 'リツ、リュウ', 'た(つ)', 'Lập', 'Người đứng trên đất.'),
(167, 1, '休', 6, 'N5', 68, 'Nghỉ ngơi', 'Rest', 'キュウ', 'やす(む)', 'Hưu', 'Người (人) tựa cây (木) = nghỉ.'),
(168, 1, '生', 5, 'N5', 69, 'Sống, sinh', 'Life, raw', 'セイ、ショウ', 'い(きる)、う(まれる)、なま', 'Sinh', 'Cây non đâm chồi = sự sống.'),
(169, 1, '学', 8, 'N5', 70, 'Học', 'Study, learn', 'ガク', 'まな(ぶ)', 'Học', 'Học sinh (子) đội mũ trí thức.'),
(170, 1, '校', 10, 'N5', 71, 'Trường', 'School', 'コウ', NULL, 'Hiệu', 'Cây (木) gốc rễ (交) = trường học cội nguồn.'),
(171, 1, '先', 6, 'N5', 72, 'Trước, đi đầu', 'Previous, ahead', 'セン', 'さき', 'Tiên', 'Người (儿) bước đi trước.'),
(172, 1, '名', 6, 'N5', 73, 'Tên', 'Name', 'メイ、ミョウ', 'な', 'Danh', 'Buổi tối (夕) + miệng (口) = gọi tên.'),
(173, 1, '今', 4, 'N5', 74, 'Bây giờ', 'Now', 'コン、キン', 'いま', 'Kim', 'Lúc hiện tại - cái này.'),
(174, 1, '時', 10, 'N5', 75, 'Giờ, thời gian', 'Time, hour', 'ジ', 'とき', 'Thời', 'Mặt trời (日) + đền (寺) = thời gian.'),
(175, 1, '年', 6, 'N5', 76, 'Năm', 'Year', 'ネン', 'とし', 'Niên', 'Người gánh lúa = một năm thu hoạch.'),
(176, 1, '何', 7, 'N5', 77, 'Cái gì', 'What', 'カ', 'なに、なん', 'Hà', 'Người (人) cầm vác (可) = vác cái gì.'),
(177, 1, '本', 5, 'N5', 78, 'Sách, gốc', 'Book, origin', 'ホン', 'もと', 'Bản', 'Cây (木) có gạch dưới = gốc rễ, nguồn.'),
(178, 1, '車', 7, 'N5', 79, 'Xe', 'Car, vehicle', 'シャ', 'くるま', 'Xa', 'Bánh xe + trục xe = xe.'),
(179, 1, '電', 13, 'N5', 80, 'Điện', 'Electric', 'デン', NULL, 'Điện', 'Mưa (雨) + sét (申) = điện.');

-- ========================
-- KANJI JLPT N4 (Selected 50+)
-- ========================
INSERT INTO characters_table (id, language_id, character_text, stroke_count, jlpt_level, frequency_rank, meaning_vi, meaning_en, on_reading, kun_reading, han_viet, mnemonic_text) VALUES
(200, 1, '会', 6, 'N4', 200, 'Gặp gỡ, hội', 'Meet, association', 'カイ、エ', 'あ(う)', 'Hội', 'Mọi người tụ họp dưới một mái nhà.'),
(201, 1, '社', 7, 'N4', 201, 'Công ty, xã hội', 'Company, society', 'シャ', 'やしろ', 'Xã', 'Đền thờ (示) + đất (土) = nơi cộng đồng.'),
(202, 1, '時', 10, 'N4', 202, 'Thời gian', 'Time', 'ジ', 'とき', 'Thời', 'Mặt trời di chuyển trong đền = thời gian.'),
(203, 1, '間', 12, 'N4', 203, 'Khoảng giữa', 'Interval', 'カン、ケン', 'あいだ、ま', 'Gian', 'Mặt trời (日) thấy qua cổng (門) = khoảng giữa.'),
(204, 1, '分', 4, 'N4', 204, 'Phần, phút', 'Part, minute', 'フン、ブン、ブ', 'わ(かる)、わ(ける)', 'Phân', 'Dao (刀) chia làm 8 (八) = phân chia.'),
(205, 1, '半', 5, 'N4', 205, 'Nửa', 'Half', 'ハン', 'なか(ば)', 'Bán', 'Bò (牛) bị chia đôi = một nửa.'),
(206, 1, '毎', 6, 'N4', 206, 'Mỗi', 'Every', 'マイ', NULL, 'Mỗi', 'Người (人) + mẹ (母) = mỗi người mỗi mẹ.'),
(207, 1, '週', 11, 'N4', 207, 'Tuần', 'Week', 'シュウ', NULL, 'Chu', 'Vòng tròn (周) đi quanh = một tuần.'),
(208, 1, '今', 4, 'N4', 208, 'Bây giờ', 'Now', 'コン、キン', 'いま', 'Kim', 'Hiện tại, ngay lúc này.'),
(209, 1, '近', 7, 'N4', 209, 'Gần', 'Near', 'キン', 'ちか(い)', 'Cận', 'Đường đi (辶) + cái rìu (斤) = đi gần.'),
(210, 1, '遠', 13, 'N4', 210, 'Xa', 'Far', 'エン、オン', 'とお(い)', 'Viễn', 'Đi (辶) + áo (袁) = đi xa.'),
(211, 1, '長', 8, 'N4', 211, 'Dài, trưởng', 'Long, leader', 'チョウ', 'なが(い)', 'Trường', 'Người tóc dài = lâu, trưởng.'),
(212, 1, '短', 12, 'N4', 212, 'Ngắn', 'Short', 'タン', 'みじか(い)', 'Đoản', 'Mũi tên (矢) + đậu (豆) = ngắn như cây đậu.'),
(213, 1, '高', 10, 'N4', 213, 'Cao', 'High, expensive', 'コウ', 'たか(い)', 'Cao', 'Tòa nhà cao tầng có 2 mái.'),
(214, 1, '安', 6, 'N4', 214, 'An toàn, rẻ', 'Safe, cheap', 'アン', 'やす(い)', 'An', 'Phụ nữ (女) trong nhà (宀) = an toàn.'),
(215, 1, '新', 13, 'N4', 215, 'Mới', 'New', 'シン', 'あたら(しい)', 'Tân', 'Đứng (立) + cây (木) + rìu (斤) = chặt cây mới.'),
(216, 1, '古', 5, 'N4', 216, 'Cũ', 'Old', 'コ', 'ふる(い)', 'Cổ', 'Mười (十) thế hệ truyền miệng (口) = cũ.'),
(217, 1, '元', 4, 'N4', 217, 'Gốc, nguồn', 'Origin', 'ゲン、ガン', 'もと', 'Nguyên', 'Đầu (二) trên người (儿) = nguồn gốc.'),
(218, 1, '気', 6, 'N4', 218, 'Khí, tinh thần', 'Spirit', 'キ、ケ', NULL, 'Khí', 'Hơi (气) + gạo (米) = năng lượng.'),
(219, 1, '色', 6, 'N4', 219, 'Màu sắc', 'Color', 'ショク、シキ', 'いろ', 'Sắc', 'Hình ảnh phụ nữ ngả vào người yêu = sắc.'),
(220, 1, '赤', 7, 'N4', 220, 'Đỏ', 'Red', 'セキ、シャク', 'あか(い)', 'Xích', 'Đất (土) + lửa (火) = màu đỏ của lửa.'),
(221, 1, '白', 5, 'N4', 221, 'Trắng', 'White', 'ハク、ビャク', 'しろ(い)', 'Bạch', 'Mặt trời (日) chiếu sáng = ánh trắng.'),
(222, 1, '黒', 11, 'N4', 222, 'Đen', 'Black', 'コク', 'くろ(い)', 'Hắc', 'Khói đen từ lửa và đất.'),
(223, 1, '青', 8, 'N4', 223, 'Xanh', 'Blue, green', 'セイ、ショウ', 'あお(い)', 'Thanh', 'Sinh (生) + tháng (月) = trẻ tươi xanh.'),
(224, 1, '夏', 10, 'N4', 224, 'Mùa hè', 'Summer', 'カ、ゲ', 'なつ', 'Hạ', 'Đầu (頁) + chân (夂) = bước nhanh trong nắng nóng.'),
(225, 1, '冬', 5, 'N4', 225, 'Mùa đông', 'Winter', 'トウ', 'ふゆ', 'Đông', 'Bước chậm (夂) trong tuyết = mùa đông.'),
(226, 1, '春', 9, 'N4', 226, 'Mùa xuân', 'Spring', 'シュン', 'はる', 'Xuân', 'Ba (三) cây (人) cỏ (日) đâm chồi.'),
(227, 1, '秋', 9, 'N4', 227, 'Mùa thu', 'Autumn', 'シュウ', 'あき', 'Thu', 'Lúa chín (禾) bị đốt (火) = mùa thu.'),
(228, 1, '朝', 12, 'N4', 228, 'Buổi sáng', 'Morning', 'チョウ', 'あさ', 'Triêu', 'Mặt trời (日) lên giữa cỏ + trăng = sáng.'),
(229, 1, '昼', 9, 'N4', 229, 'Buổi trưa', 'Noon', 'チュウ', 'ひる', 'Trú', 'Mặt trời (日) ở đỉnh đầu.'),
(230, 1, '夜', 8, 'N4', 230, 'Đêm', 'Night', 'ヤ', 'よる、よ', 'Dạ', 'Mái nhà (亠) + chân + đêm khuya.'),
(231, 1, '雪', 11, 'N4', 231, 'Tuyết', 'Snow', 'セツ', 'ゆき', 'Tuyết', 'Mưa (雨) + tay (彐) = quét tuyết.'),
(232, 1, '風', 9, 'N4', 232, 'Gió', 'Wind', 'フウ、フ', 'かぜ', 'Phong', 'Gió thổi côn trùng (虫) bay qua bụi cây.'),
(233, 1, '雲', 12, 'N4', 233, 'Mây', 'Cloud', 'ウン', 'くも', 'Vân', 'Mưa (雨) + nói (云) = mây trên trời.'),
(234, 1, '空', 8, 'N4', 234, 'Bầu trời', 'Sky, empty', 'クウ', 'そら、あ(く)', 'Không', 'Hang (穴) + công việc (工) = trống không.'),
(235, 1, '海', 9, 'N4', 235, 'Biển', 'Sea', 'カイ', 'うみ', 'Hải', 'Nước (氵) + mỗi (毎) = mọi nơi đều có biển.'),
(236, 1, '島', 10, 'N4', 236, 'Đảo', 'Island', 'トウ', 'しま', 'Đảo', 'Chim (鳥) đậu trên núi (山) trên biển.'),
(237, 1, '駅', 14, 'N4', 237, 'Ga (tàu)', 'Station', 'エキ', NULL, 'Trạm', 'Ngựa (馬) + thước (尺) = nơi dừng chân.'),
(238, 1, '通', 10, 'N4', 238, 'Đi qua', 'Pass through', 'ツウ', 'とお(る)、かよ(う)', 'Thông', 'Đi (辶) + dấu thông qua = đi qua.'),
(239, 1, '走', 7, 'N4', 239, 'Chạy', 'Run', 'ソウ', 'はし(る)', 'Tẩu', 'Đất (土) + chân (儿) = chạy.'),
(240, 1, '帰', 10, 'N4', 240, 'Về', 'Return', 'キ', 'かえ(る)', 'Quy', 'Hình người vác đồ về nhà.'),
(241, 1, '使', 8, 'N4', 241, 'Sử dụng', 'Use', 'シ', 'つか(う)', 'Sử', 'Người (人) + lịch sử (史) = sai khiến.'),
(242, 1, '働', 13, 'N4', 242, 'Làm việc', 'Work', 'ドウ', 'はたら(く)', 'Động', 'Người (人) + di chuyển (動) = lao động.'),
(243, 1, '勉', 10, 'N4', 243, 'Cố gắng', 'Effort', 'ベン', NULL, 'Miễn', 'Cùng (兔 dạng giản) + sức (力) = nỗ lực.'),
(244, 1, '強', 11, 'N4', 244, 'Mạnh', 'Strong', 'キョウ、ゴウ', 'つよ(い)', 'Cường', 'Cung (弓) + côn trùng = mạnh mẽ.'),
(245, 1, '弱', 10, 'N4', 245, 'Yếu', 'Weak', 'ジャク', 'よわ(い)', 'Nhược', 'Hai cánh cung yếu rủ xuống.'),
(246, 1, '正', 5, 'N4', 246, 'Đúng', 'Correct', 'セイ、ショウ', 'ただ(しい)', 'Chính', 'Một (一) + dừng (止) = đúng chỗ.'),
(247, 1, '悪', 11, 'N4', 247, 'Xấu', 'Bad, evil', 'アク、オ', 'わる(い)', 'Ác', 'Á (亜) + tâm (心) = xấu trong lòng.'),
(248, 1, '便', 9, 'N4', 248, 'Tiện lợi', 'Convenient', 'ベン、ビン', NULL, 'Tiện', 'Người (人) + thay đổi (更) = tiện ích.'),
(249, 1, '利', 7, 'N4', 249, 'Lợi ích', 'Profit', 'リ', 'き(く)', 'Lợi', 'Lúa (禾) + dao (刂) = thu hoạch lợi nhuận.'),
(250, 1, '思', 9, 'N4', 250, 'Nghĩ', 'Think', 'シ', 'おも(う)', 'Tư', 'Đầu (田) + tâm (心) = suy nghĩ.');

-- ========================
-- HANZI HSK 1-2 (Chinese characters - language_id = 3)
-- ========================
INSERT INTO characters_table (id, language_id, character_text, stroke_count, jlpt_level, frequency_rank, meaning_vi, meaning_en, on_reading, kun_reading, han_viet, mnemonic_text) VALUES
-- HSK 1 numbers
(300, 3, '一', 1, 'HSK1', 1, 'Một', 'One', 'yī', NULL, 'Nhất', 'Một nét ngang.'),
(301, 3, '二', 2, 'HSK1', 2, 'Hai', 'Two', 'èr', NULL, 'Nhị', 'Hai nét ngang.'),
(302, 3, '三', 3, 'HSK1', 3, 'Ba', 'Three', 'sān', NULL, 'Tam', 'Ba nét ngang.'),
(303, 3, '四', 5, 'HSK1', 4, 'Bốn', 'Four', 'sì', NULL, 'Tứ', 'Hộp với 2 chân.'),
(304, 3, '五', 4, 'HSK1', 5, 'Năm', 'Five', 'wǔ', NULL, 'Ngũ', 'Số 5.'),
(305, 3, '六', 4, 'HSK1', 6, 'Sáu', 'Six', 'liù', NULL, 'Lục', 'Mái nhà.'),
(306, 3, '七', 2, 'HSK1', 7, 'Bảy', 'Seven', 'qī', NULL, 'Thất', 'Lưỡi liềm.'),
(307, 3, '八', 2, 'HSK1', 8, 'Tám', 'Eight', 'bā', NULL, 'Bát', 'Hai cánh.'),
(308, 3, '九', 2, 'HSK1', 9, 'Chín', 'Nine', 'jiǔ', NULL, 'Cửu', 'Số 9.'),
(309, 3, '十', 2, 'HSK1', 10, 'Mười', 'Ten', 'shí', NULL, 'Thập', 'Dấu cộng = 10.'),
-- HSK 1 People
(310, 3, '人', 2, 'HSK1', 11, 'Người', 'Person', 'rén', NULL, 'Nhân', 'Người đứng.'),
(311, 3, '我', 7, 'HSK1', 12, 'Tôi', 'I, me', 'wǒ', NULL, 'Ngã', 'Tay (手) cầm vũ khí (戈) = tôi.'),
(312, 3, '你', 7, 'HSK1', 13, 'Bạn', 'You', 'nǐ', NULL, 'Nhĩ', 'Người (亻) + nhỏ (尔) = bạn.'),
(313, 3, '他', 5, 'HSK1', 14, 'Anh ấy', 'He', 'tā', NULL, 'Tha', 'Người (亻) khác.'),
(314, 3, '她', 6, 'HSK1', 15, 'Cô ấy', 'She', 'tā', NULL, 'Tha', 'Phụ nữ (女) khác = cô ấy.'),
(315, 3, '们', 5, 'HSK1', 16, 'Số nhiều', 'Plural marker', 'men', NULL, 'Môn', 'Người (亻) + cổng (门) = nhiều người.'),
(316, 3, '老', 6, 'HSK1', 17, 'Già', 'Old', 'lǎo', NULL, 'Lão', 'Người già chống gậy.'),
(317, 3, '师', 6, 'HSK1', 18, 'Thầy', 'Master, teacher', 'shī', NULL, 'Sư', 'Người dẫn dắt.'),
(318, 3, '学', 8, 'HSK1', 19, 'Học', 'Study', 'xué', NULL, 'Học', 'Trẻ con học chữ.'),
(319, 3, '生', 5, 'HSK1', 20, 'Sống, sinh', 'Live, born', 'shēng', NULL, 'Sinh', 'Mầm cây mọc lên.'),
-- HSK 1 Common
(320, 3, '不', 4, 'HSK1', 21, 'Không', 'Not', 'bù', NULL, 'Bất', 'Phủ định.'),
(321, 3, '是', 9, 'HSK1', 22, 'Là', 'Be', 'shì', NULL, 'Thị', 'Mặt trời (日) đúng (正) = là đúng.'),
(322, 3, '有', 6, 'HSK1', 23, 'Có', 'Have', 'yǒu', NULL, 'Hữu', 'Tay cầm thịt = có.'),
(323, 3, '没', 7, 'HSK1', 24, 'Không có', 'Not have', 'méi', NULL, 'Mộc', 'Nước (氵) + vào trong = chìm xuống không có.'),
(324, 3, '好', 6, 'HSK1', 25, 'Tốt', 'Good', 'hǎo', NULL, 'Hảo', 'Phụ nữ (女) + con (子) = mẹ con là tốt.'),
(325, 3, '大', 3, 'HSK1', 26, 'Lớn', 'Big', 'dà', NULL, 'Đại', 'Người dang tay = lớn.'),
(326, 3, '小', 3, 'HSK1', 27, 'Nhỏ', 'Small', 'xiǎo', NULL, 'Tiểu', 'Ba chấm nhỏ.'),
(327, 3, '多', 6, 'HSK1', 28, 'Nhiều', 'Many', 'duō', NULL, 'Đa', 'Hai buổi tối (夕) chồng lên = nhiều.'),
(328, 3, '少', 4, 'HSK1', 29, 'Ít', 'Few', 'shǎo', NULL, 'Thiểu', 'Nhỏ (小) + một chấm = ít hơn.'),
(329, 3, '上', 3, 'HSK1', 30, 'Trên', 'Up', 'shàng', NULL, 'Thượng', 'Trên đường ngang.'),
(330, 3, '下', 3, 'HSK1', 31, 'Dưới', 'Down', 'xià', NULL, 'Hạ', 'Dưới đường ngang.'),
(331, 3, '中', 4, 'HSK1', 32, 'Giữa', 'Middle', 'zhōng', NULL, 'Trung', 'Mũi tên xuyên ô vuông.'),
(332, 3, '国', 8, 'HSK1', 33, 'Nước', 'Country', 'guó', NULL, 'Quốc', 'Vua (王) trong khu vực (口).'),
(333, 3, '中国', 4, 'HSK1', 34, 'Trung Quốc', 'China', 'zhōng guó', NULL, 'Trung Quốc', 'Đất nước trung tâm.'),
(334, 3, '日', 4, 'HSK1', 35, 'Ngày', 'Day, sun', 'rì', NULL, 'Nhật', 'Mặt trời.'),
(335, 3, '月', 4, 'HSK1', 36, 'Tháng', 'Moon, month', 'yuè', NULL, 'Nguyệt', 'Mặt trăng.'),
(336, 3, '年', 6, 'HSK1', 37, 'Năm', 'Year', 'nián', NULL, 'Niên', 'Người gánh lúa = một năm.'),
(337, 3, '今', 4, 'HSK1', 38, 'Nay', 'Now', 'jīn', NULL, 'Kim', 'Hiện tại.'),
(338, 3, '天', 4, 'HSK1', 39, 'Trời, ngày', 'Sky, day', 'tiān', NULL, 'Thiên', 'Đầu lớn (大) trên một (一) = bầu trời.'),
(339, 3, '明', 8, 'HSK1', 40, 'Sáng', 'Bright', 'míng', NULL, 'Minh', 'Mặt trời (日) + mặt trăng (月) = sáng.'),
(340, 3, '昨', 9, 'HSK1', 41, 'Hôm qua', 'Yesterday', 'zuó', NULL, 'Tạc', 'Mặt trời (日) + lúc trước (乍) = hôm qua.'),
(341, 3, '在', 6, 'HSK1', 42, 'Ở, đang', 'At, in', 'zài', NULL, 'Tại', 'Đất (土) + chỗ = đang ở.'),
(342, 3, '来', 7, 'HSK1', 43, 'Đến', 'Come', 'lái', NULL, 'Lai', 'Cây lúa chín = đến mùa thu hoạch.'),
(343, 3, '去', 5, 'HSK1', 44, 'Đi', 'Go', 'qù', NULL, 'Khứ', 'Đất (土) + tư (厶) = rời đi.'),
(344, 3, '看', 9, 'HSK1', 45, 'Nhìn, xem', 'Look', 'kàn', NULL, 'Khán', 'Tay (手) trên mắt (目) = nhìn xa.'),
(345, 3, '听', 7, 'HSK1', 46, 'Nghe', 'Listen', 'tīng', NULL, 'Thính', 'Miệng (口) + cân (斤) = nghe cẩn thận.'),
(346, 3, '说', 9, 'HSK1', 47, 'Nói', 'Speak', 'shuō', NULL, 'Thuyết', 'Ngôn (讠) + đổi (兑) = nói chuyện.'),
(347, 3, '吃', 6, 'HSK1', 48, 'Ăn', 'Eat', 'chī', NULL, 'Cật', 'Miệng (口) + ăn = nhai.'),
(348, 3, '喝', 12, 'HSK1', 49, 'Uống', 'Drink', 'hē', NULL, 'Hạt', 'Miệng (口) + cảm (曷) = uống.'),
(349, 3, '水', 4, 'HSK1', 50, 'Nước', 'Water', 'shuǐ', NULL, 'Thủy', 'Dòng nước chảy.'),
(350, 3, '茶', 9, 'HSK1', 51, 'Trà', 'Tea', 'chá', NULL, 'Trà', 'Cỏ (艹) + người (人) + cây (木) = lá trà.'),
(351, 3, '书', 4, 'HSK1', 52, 'Sách', 'Book', 'shū', NULL, 'Thư', 'Bút viết trên giấy.'),
(352, 3, '字', 6, 'HSK1', 53, 'Chữ', 'Character', 'zì', NULL, 'Tự', 'Mái nhà (宀) + con (子) = học chữ.'),
(353, 3, '家', 10, 'HSK1', 54, 'Nhà', 'Home', 'jiā', NULL, 'Gia', 'Mái nhà (宀) + heo (豕) = ngôi nhà.'),
(354, 3, '车', 4, 'HSK1', 55, 'Xe', 'Vehicle', 'chē', NULL, 'Xa', 'Bánh xe.'),
(355, 3, '时', 7, 'HSK1', 56, 'Thời gian', 'Time', 'shí', NULL, 'Thời', 'Mặt trời (日) + đền (寺) = thời gian.'),
(356, 3, '点', 9, 'HSK1', 57, 'Điểm, giờ', 'Dot, hour', 'diǎn', NULL, 'Điểm', 'Lửa (灬) + chiếm (占) = đốm sáng.'),
(357, 3, '钱', 10, 'HSK1', 58, 'Tiền', 'Money', 'qián', NULL, 'Tiền', 'Vàng (钅) + nhỏ (戋) = tiền nhỏ lẻ.'),
(358, 3, '买', 6, 'HSK1', 59, 'Mua', 'Buy', 'mǎi', NULL, 'Mãi', 'Đầu (亠) + lớn (大) = mua lớn.'),
(359, 3, '卖', 8, 'HSK1', 60, 'Bán', 'Sell', 'mài', NULL, 'Mại', 'Đầu (亠) + đất (土) + lớn = bán.');

-- ========================
-- GRAMMAR JAPANESE (extended) - JLPT N5/N4
-- ========================
INSERT INTO grammars (id, language_id, pattern, meaning_vi, meaning_en, structure, jlpt_level, example_sentence, example_translation, note) VALUES
-- N5 grammar (continuing from existing 1-3)
(100, 1, '〜が好きです', 'Thích ~', 'I like ~', 'Danh từ + が好きです', 'N5', 'わたしはねこがすきです。', 'Tôi thích mèo.', 'Trợ từ が dùng với すき/きらい/じょうず/へた.'),
(101, 1, '〜が嫌いです', 'Ghét ~', 'I dislike ~', 'Danh từ + が嫌いです', 'N5', 'わたしはトマトがきらいです。', 'Tôi ghét cà chua.', 'Cấu trúc tương tự すき.'),
(102, 1, '〜があります', 'Có ~ (vật)', 'There is ~ (thing)', 'Danh từ + があります', 'N5', 'つくえのうえにほんがあります。', 'Có sách trên bàn.', 'Dùng cho vật vô tri.'),
(103, 1, '〜がいます', 'Có ~ (người/động vật)', 'There is ~ (animate)', 'Danh từ + がいます', 'N5', 'こうえんにこどもがいます。', 'Có trẻ con ở công viên.', 'Dùng cho người và động vật.'),
(104, 1, '〜を + Verb', 'Tân ngữ + động từ', 'Object + verb', 'Danh từ + を + Vます', 'N5', 'ほんをよみます。', 'Đọc sách.', 'を là trợ từ tân ngữ trực tiếp.'),
(105, 1, '〜に行きます', 'Đi đến ~', 'Go to ~', 'Địa điểm + に + 行きます', 'N5', 'がっこうにいきます。', 'Đi đến trường.', 'に chỉ điểm đến của hành động.'),
(106, 1, '〜で + Vます', 'Tại/bằng ~ làm gì', 'At/by ~ do something', 'Nơi/phương tiện + で + Vます', 'N5', 'バスでがっこうにいきます。', 'Đi đến trường bằng xe buýt.', 'で chỉ phương tiện hoặc nơi diễn ra hành động.'),
(107, 1, '〜と + Vます', 'Cùng với ~', 'Together with ~', 'Người + と + Vます', 'N5', 'ともだちとはなします。', 'Nói chuyện với bạn.', 'と chỉ người cùng làm.'),
(108, 1, '〜から〜まで', 'Từ ~ đến ~', 'From ~ to ~', '〜から〜まで', 'N5', '9じから5じまではたらきます。', 'Làm việc từ 9 giờ đến 5 giờ.', 'Dùng cho cả thời gian và không gian.'),
(109, 1, 'Vませんか', 'Cùng làm ~ không?', 'Won''t you ~?', 'Vます stem + ませんか', 'N5', 'いっしょにえいがをみませんか。', 'Cùng xem phim không?', 'Lời mời lịch sự.'),
(110, 1, 'Vましょう', 'Hãy cùng ~', 'Let''s ~', 'Vます stem + ましょう', 'N5', 'べんきょうしましょう。', 'Hãy cùng học.', 'Lời rủ rê.'),
(111, 1, 'Vたいです', 'Muốn ~', 'Want to ~', 'Vます stem + たいです', 'N5', 'にほんへいきたいです。', 'Tôi muốn đi Nhật.', 'Diễn tả mong muốn của mình.'),
(112, 1, 'Vてください', 'Hãy ~', 'Please ~', 'Vて + ください', 'N5', 'まどをあけてください。', 'Hãy mở cửa sổ.', 'Yêu cầu lịch sự.'),
(113, 1, 'Vている', 'Đang ~', 'Be ~ing', 'Vて + いる', 'N5', 'いまべんきょうしています。', 'Bây giờ tôi đang học.', 'Hành động đang diễn ra hoặc trạng thái.'),
(114, 1, 'Adj-い', 'Tính từ đuôi い', 'I-adjective', 'い-Adj', 'N5', 'このりんごはあかいです。', 'Quả táo này đỏ.', 'Tính từ kết thúc bằng い.'),
(115, 1, 'Adj-な', 'Tính từ đuôi な', 'Na-adjective', 'な-Adj + な + N', 'N5', 'きれいなはなです。', 'Là bông hoa đẹp.', 'Cần な khi đứng trước danh từ.'),
(116, 1, 'い-Adj past', 'Quá khứ tính từ い', 'Past form of i-adj', 'い → かった + です', 'N5', 'きのうはあつかったです。', 'Hôm qua trời nóng.', 'Bỏ い → かった.'),
(117, 1, 'い-Adj negative', 'Phủ định tính từ い', 'Negative i-adj', 'い → くないです', 'N5', 'これはあまくないです。', 'Cái này không ngọt.', 'Bỏ い → くない.'),
(118, 1, 'V-ない form', 'Phủ định động từ', 'Negative form', 'V → ない', 'N5', 'にくをたべない。', 'Tôi không ăn thịt.', 'Thể phủ định thông thường.'),
(119, 1, '〜より〜のほうが', '~ hơn ~', '~ is more than ~', 'AよりBのほうが + Adj', 'N5', 'りんごよりみかんのほうがすきです。', 'Tôi thích quýt hơn táo.', 'So sánh hai vật/người.');

-- N4 grammar
INSERT INTO grammars (id, language_id, pattern, meaning_vi, meaning_en, structure, jlpt_level, example_sentence, example_translation, note) VALUES
(200, 1, '〜と思います', 'Tôi nghĩ rằng ~', 'I think that ~', 'Plain form + と思います', 'N4', 'あしたあめがふるとおもいます。', 'Tôi nghĩ ngày mai sẽ mưa.', 'Diễn tả ý kiến cá nhân.'),
(201, 1, '〜と言います', 'Nói rằng ~', '~ said that ~', 'Plain form + と言います', 'N4', 'たなかさんはいきますといいました。', 'Anh Tanaka nói sẽ đi.', 'Trích dẫn lời nói.'),
(202, 1, '〜ことができる', 'Có thể ~', 'Can ~', 'V dictionary + ことができる', 'N4', 'にほんごをはなすことができます。', 'Tôi có thể nói tiếng Nhật.', 'Thể hiện khả năng.'),
(203, 1, '〜たことがある', 'Đã từng ~', 'Have ~ before', 'Vた + ことがある', 'N4', 'にほんへいったことがあります。', 'Tôi đã từng đi Nhật.', 'Kinh nghiệm trong quá khứ.'),
(204, 1, '〜ながら', 'Vừa ~ vừa ~', 'While ~', 'Vます stem + ながら', 'N4', 'おんがくをききながらべんきょうします。', 'Vừa nghe nhạc vừa học.', 'Hai hành động cùng lúc.'),
(205, 1, '〜たり〜たり', 'Vừa ~ vừa ~ (liệt kê)', 'Doing ~ and ~', 'Vた + り Vた + りする', 'N4', 'にちようびはほんをよんだり、おんがくをきいたりします。', 'Chủ nhật tôi đọc sách và nghe nhạc.', 'Liệt kê các hành động.'),
(206, 1, '〜なければならない', 'Phải ~', 'Must ~', 'Vない → なければならない', 'N4', 'べんきょうしなければなりません。', 'Tôi phải học bài.', 'Nghĩa vụ, bắt buộc.'),
(207, 1, '〜てもいい', 'Được phép ~', 'May ~', 'Vて + もいい', 'N4', 'うちにかえってもいいですか。', 'Tôi về nhà được không?', 'Xin phép.'),
(208, 1, '〜てはいけない', 'Không được ~', 'Must not ~', 'Vて + はいけない', 'N4', 'ここでたばこをすってはいけません。', 'Không được hút thuốc ở đây.', 'Cấm đoán.'),
(209, 1, '〜ようになる', 'Trở nên ~', 'Become able to ~', 'V dict + ようになる', 'N4', 'にほんごがはなせるようになりました。', 'Tôi đã có thể nói tiếng Nhật.', 'Thay đổi về khả năng/thói quen.'),
(210, 1, '〜つもりです', 'Định ~', 'Plan to ~', 'V dict + つもりです', 'N4', 'らいねんにほんへいくつもりです。', 'Năm sau tôi định đi Nhật.', 'Dự định trong tương lai.'),
(211, 1, '〜ば〜', 'Nếu ~ thì ~', 'If ~', 'V conditional ば', 'N4', 'やすければかいます。', 'Nếu rẻ thì tôi mua.', 'Câu điều kiện.'),
(212, 1, '〜たら〜', 'Khi/Nếu ~ thì ~', 'When/If ~', 'Vた + ら', 'N4', 'いえにかえったら、でんわします。', 'Khi về nhà tôi sẽ gọi.', 'Điều kiện thời gian.'),
(213, 1, '〜と〜', 'Hễ ~ thì ~', 'When ~', 'V dict + と', 'N4', 'はるになると、はながさきます。', 'Hễ đến mùa xuân thì hoa nở.', 'Quy luật tự nhiên.');

-- ========================
-- GRAMMAR ENGLISH - CEFR A1/A2
-- ========================
INSERT INTO grammars (id, language_id, pattern, meaning_vi, meaning_en, structure, jlpt_level, example_sentence, example_translation, note) VALUES
(300, 2, 'Present Simple', 'Hiện tại đơn', 'Present simple tense', 'S + V(s/es)', 'A1', 'I work in London.', 'Tôi làm việc ở London.', 'Diễn tả thói quen, sự thật. Thêm s/es với ngôi 3 số ít.'),
(301, 2, 'Present Continuous', 'Hiện tại tiếp diễn', 'Present continuous', 'S + am/is/are + V-ing', 'A1', 'She is reading now.', 'Cô ấy đang đọc sách.', 'Hành động đang diễn ra tại thời điểm nói.'),
(302, 2, 'Past Simple', 'Quá khứ đơn', 'Past simple tense', 'S + V2/ed', 'A1', 'I visited Paris last year.', 'Tôi đã đến Paris năm ngoái.', 'Hành động đã hoàn thành trong quá khứ.'),
(303, 2, 'Future (will)', 'Tương lai (will)', 'Future with will', 'S + will + V', 'A1', 'I will call you tomorrow.', 'Tôi sẽ gọi cho bạn ngày mai.', 'Quyết định tức thời, dự đoán.'),
(304, 2, 'Future (be going to)', 'Tương lai (going to)', 'Be going to', 'S + am/is/are + going to + V', 'A1', 'We are going to eat.', 'Chúng tôi sẽ ăn.', 'Kế hoạch, dự định đã có sẵn.'),
(305, 2, 'A / An', 'Mạo từ a/an', 'Articles a/an', 'a + consonant; an + vowel', 'A1', 'a book, an apple', 'một quyển sách, một quả táo', 'A trước phụ âm, An trước nguyên âm.'),
(306, 2, 'The', 'Mạo từ the', 'Definite article', 'the + N (specific)', 'A1', 'The book on the table.', 'Quyển sách trên bàn.', 'Dùng khi xác định cụ thể.'),
(307, 2, 'Possessive ''s', 'Sở hữu cách', 'Possessive ''s', 'N + ''s + N', 'A1', 'John''s car.', 'Xe của John.', 'Sở hữu của người.'),
(308, 2, 'Possessive Adjectives', 'Tính từ sở hữu', 'My, your, his, her, its, our, their', 'PossAdj + N', 'A1', 'This is my book.', 'Đây là sách của tôi.', '7 tính từ sở hữu cơ bản.'),
(309, 2, 'There is / There are', 'Có ~', 'There is/are', 'There is + sing N; There are + plu N', 'A1', 'There is a cat. There are 3 cats.', 'Có một con mèo. Có 3 con mèo.', 'Diễn tả sự tồn tại.'),
(310, 2, 'Can (ability)', 'Có thể (khả năng)', 'Can for ability', 'S + can + V', 'A1', 'I can swim.', 'Tôi có thể bơi.', 'Khả năng làm việc gì.'),
(311, 2, 'Can (permission)', 'Có thể (xin phép)', 'Can for permission', 'Can + S + V?', 'A1', 'Can I go now?', 'Tôi có thể đi không?', 'Xin phép.'),
(312, 2, 'Must (obligation)', 'Phải (bắt buộc)', 'Must for obligation', 'S + must + V', 'A1', 'You must wear a helmet.', 'Bạn phải đội mũ bảo hiểm.', 'Sự bắt buộc.'),
(313, 2, 'Should (advice)', 'Nên (khuyên)', 'Should for advice', 'S + should + V', 'A1', 'You should rest more.', 'Bạn nên nghỉ ngơi nhiều hơn.', 'Lời khuyên.'),
(314, 2, 'Would like', 'Muốn (lịch sự)', 'Would like to', 'S + would like + N/to V', 'A1', 'I would like a coffee.', 'Tôi muốn một ly cà phê.', 'Cách nói lịch sự cho ''want''.'),
(315, 2, 'Prepositions of time', 'Giới từ thời gian', 'in/on/at for time', 'in (year/month), on (day), at (time)', 'A1', 'in 2025, on Monday, at 5pm', 'năm 2025, thứ Hai, 5h chiều', 'in - tháng/năm, on - ngày, at - giờ.'),
(316, 2, 'Prepositions of place', 'Giới từ chỉ nơi chốn', 'in/on/at for place', 'in (large area), on (surface), at (point)', 'A1', 'in the room, on the table, at the door', 'trong phòng, trên bàn, ở cửa', 'in - không gian kín, on - bề mặt, at - điểm.'),
(317, 2, 'Comparatives', 'So sánh hơn', 'Comparative adjectives', 'Adj-er than / more Adj than', 'A1', 'He is taller than me.', 'Anh ấy cao hơn tôi.', 'Tính từ ngắn + er, dài + more.'),
(318, 2, 'Superlatives', 'So sánh nhất', 'Superlative adjectives', 'the + Adj-est / the most Adj', 'A1', 'The tallest building.', 'Tòa nhà cao nhất.', 'Tính từ ngắn + est, dài + most.'),
(319, 2, 'Quantifiers (some/any)', 'Một vài / nào đó', 'Some / Any', 'some (positive), any (negative/question)', 'A2', 'I have some money. Do you have any money?', 'Tôi có ít tiền. Bạn có tiền không?', 'some khẳng định, any phủ định/câu hỏi.'),
(320, 2, 'Present Perfect', 'Hiện tại hoàn thành', 'Present perfect', 'S + have/has + V3', 'A2', 'I have visited Japan.', 'Tôi đã từng thăm Nhật Bản.', 'Kinh nghiệm hoặc hành động vừa hoàn thành.'),
(321, 2, 'Past Continuous', 'Quá khứ tiếp diễn', 'Past continuous', 'S + was/were + V-ing', 'A2', 'I was reading when she called.', 'Tôi đang đọc sách khi cô ấy gọi.', 'Hành động đang xảy ra trong quá khứ.'),
(322, 2, 'Used to', 'Đã từng', 'Used to + V', 'S + used to + V', 'A2', 'I used to live in Hanoi.', 'Tôi đã từng sống ở Hà Nội.', 'Thói quen trong quá khứ không còn nữa.'),
(323, 2, 'First Conditional', 'Câu điều kiện loại 1', 'If + present, will + V', 'If + S + V (pres), S + will + V', 'A2', 'If it rains, I will stay home.', 'Nếu trời mưa, tôi sẽ ở nhà.', 'Điều kiện có thể xảy ra.'),
(324, 2, 'Imperatives', 'Câu mệnh lệnh', 'Commands', 'V (base form)', 'A1', 'Sit down. Don''t talk!', 'Ngồi xuống. Đừng nói chuyện!', 'Lệnh, yêu cầu trực tiếp.'),
(325, 2, 'Wh-questions', 'Câu hỏi với từ Wh-', 'Wh- questions', 'Wh + aux + S + V?', 'A1', 'Where do you live?', 'Bạn sống ở đâu?', 'What/Where/When/Why/Who/How.');

-- ========================
-- GRAMMAR CHINESE - HSK 1/2/3
-- ========================
INSERT INTO grammars (id, language_id, pattern, meaning_vi, meaning_en, structure, jlpt_level, example_sentence, example_translation, note) VALUES
(400, 3, '是 (shì)', 'Là', 'To be', 'S + 是 + N', 'HSK1', '我是学生。', 'Tôi là học sinh.', 'Động từ ''là'' căn bản.'),
(401, 3, '不是 (bú shì)', 'Không phải là', 'Not be', 'S + 不是 + N', 'HSK1', '我不是老师。', 'Tôi không phải là giáo viên.', 'Phủ định của 是.'),
(402, 3, '吗 (ma)', '...phải không?', 'Yes/No question', 'S + V + 吗?', 'HSK1', '你是学生吗？', 'Bạn có phải là học sinh không?', 'Trợ từ tạo câu hỏi yes/no.'),
(403, 3, '呢 (ne)', '...thì sao?', 'And what about...?', 'N + 呢?', 'HSK1', '我很好，你呢？', 'Tôi khỏe, còn bạn?', 'Hỏi lại đối phương.'),
(404, 3, '的 (de)', 'Của', 'Possessive marker', 'A + 的 + N', 'HSK1', '我的书。', 'Sách của tôi.', 'Trợ từ sở hữu.'),
(405, 3, '在 (zài)', 'Đang/Ở', 'At, in (location)', 'S + 在 + Place', 'HSK1', '我在家。', 'Tôi ở nhà.', 'Chỉ vị trí hoặc đang làm.'),
(406, 3, '有 (yǒu)', 'Có', 'Have', 'S + 有 + N', 'HSK1', '我有一本书。', 'Tôi có một quyển sách.', 'Sở hữu hoặc tồn tại.'),
(407, 3, '没有 (méi yǒu)', 'Không có', 'Not have', 'S + 没有 + N', 'HSK1', '我没有钱。', 'Tôi không có tiền.', 'Phủ định của 有.'),
(408, 3, '很 (hěn)', 'Rất', 'Very', '很 + Adj', 'HSK1', '我很高兴。', 'Tôi rất vui.', 'Bắt buộc trước tính từ trong câu khẳng định.'),
(409, 3, '太...了', 'Quá ~', 'Too ~', '太 + Adj + 了', 'HSK1', '太好了！', 'Tốt quá!', 'Cảm thán quá mức.'),
(410, 3, '会 (huì)', 'Biết, có thể', 'Can (learned)', 'S + 会 + V', 'HSK1', '我会说汉语。', 'Tôi biết nói tiếng Trung.', 'Khả năng học được.'),
(411, 3, '能 (néng)', 'Có thể', 'Can (possible)', 'S + 能 + V', 'HSK1', '我能去。', 'Tôi có thể đi.', 'Khả năng vật lý hoặc cho phép.'),
(412, 3, '想 (xiǎng)', 'Muốn, nghĩ', 'Want, think', 'S + 想 + V', 'HSK1', '我想吃苹果。', 'Tôi muốn ăn táo.', 'Mong muốn hoặc suy nghĩ.'),
(413, 3, '要 (yào)', 'Muốn, sẽ', 'Want, will', 'S + 要 + V', 'HSK1', '我要去北京。', 'Tôi muốn đi Bắc Kinh.', 'Mong muốn hoặc kế hoạch.'),
(414, 3, '了 (le) - completion', 'Đã (hoàn thành)', 'Completed action', 'V + 了', 'HSK1', '我吃饭了。', 'Tôi đã ăn cơm rồi.', 'Trợ từ chỉ hoàn thành.'),
(415, 3, '了 (le) - change', 'Đã (thay đổi)', 'Change of state', 'S + Adj + 了', 'HSK1', '天气热了。', 'Trời nóng rồi.', 'Sự thay đổi trạng thái.'),
(416, 3, '吧 (ba)', '...nhé/...thôi', 'Suggestion/assumption', 'S + V + 吧', 'HSK1', '我们走吧。', 'Chúng ta đi thôi.', 'Đề nghị hoặc phỏng đoán.'),
(417, 3, '都 (dōu)', 'Đều, tất cả', 'All, both', 'S + 都 + V', 'HSK1', '我们都喜欢。', 'Chúng tôi đều thích.', 'Đứng trước động từ.'),
(418, 3, '和 (hé)', 'Và', 'And', 'A + 和 + B', 'HSK1', '我和你。', 'Tôi và bạn.', 'Liên từ ''và''.'),
(419, 3, '比 (bǐ)', 'So với', 'Comparison', 'A + 比 + B + Adj', 'HSK2', '我比你高。', 'Tôi cao hơn bạn.', 'Câu so sánh hơn.'),
(420, 3, '正在...呢', 'Đang ~', 'Be -ing', '正在 + V + 呢', 'HSK2', '我正在吃饭呢。', 'Tôi đang ăn cơm.', 'Hành động đang tiếp diễn.'),
(421, 3, '过 (guo)', 'Đã từng', 'Have ever ~', 'V + 过', 'HSK2', '我去过北京。', 'Tôi đã từng đến Bắc Kinh.', 'Kinh nghiệm.'),
(422, 3, '一边...一边', 'Vừa ~ vừa ~', 'While ~', '一边 + V1 + 一边 + V2', 'HSK2', '一边吃饭一边看电视。', 'Vừa ăn cơm vừa xem TV.', 'Hai hành động đồng thời.'),
(423, 3, '从...到...', 'Từ ~ đến ~', 'From ~ to ~', '从 + A + 到 + B', 'HSK2', '从家到学校。', 'Từ nhà đến trường.', 'Khoảng cách hoặc thời gian.'),
(424, 3, '虽然...但是', 'Mặc dù... nhưng', 'Although... but', '虽然 + S1, 但是 + S2', 'HSK3', '虽然累，但是开心。', 'Mặc dù mệt nhưng vui.', 'Mệnh đề nhượng bộ.'),
(425, 3, '因为...所以', 'Vì... nên', 'Because... so', '因为 + S1, 所以 + S2', 'HSK3', '因为下雨，所以不去。', 'Vì trời mưa nên không đi.', 'Mệnh đề nhân quả.');
