-- =====================================================
-- LINGUA PLATFORM - Seed Data V8
-- Chinese Hanzi (HSK 1, HSK 2) - 100+ characters
-- Source: Hewgill HSK, HanyuPinyin
-- =====================================================

-- ========================
-- CHINESE HANZI - HSK 1 (50 chars)
-- language_id = 3 (Chinese)
-- IDs 600-699 reserved for HSK Hanzi
-- ========================
INSERT INTO characters_table (id, language_id, character_text, stroke_count, hsk_level, pinyin, han_viet, meaning_vi, meaning_en, mnemonic_text) VALUES
(600, 3, '人', 2, 'HSK1', 'rén', 'nhân', 'người', 'person', 'Hai chân đi bộ - chỉ một con người'),
(601, 3, '大', 3, 'HSK1', 'dà', 'đại', 'lớn, to', 'big', 'Người dang tay ra - rất lớn'),
(602, 3, '小', 3, 'HSK1', 'xiǎo', 'tiểu', 'nhỏ, bé', 'small', 'Ba chấm nhỏ tí xíu'),
(603, 3, '一', 1, 'HSK1', 'yī', 'nhất', 'một, số 1', 'one', 'Một nét ngang đơn giản'),
(604, 3, '二', 2, 'HSK1', 'èr', 'nhị', 'hai, số 2', 'two', 'Hai nét ngang chồng lên'),
(605, 3, '三', 3, 'HSK1', 'sān', 'tam', 'ba, số 3', 'three', 'Ba nét ngang chồng nhau'),
(606, 3, '四', 5, 'HSK1', 'sì', 'tứ', 'bốn, số 4', 'four', 'Hình vuông như 4 mùa'),
(607, 3, '五', 4, 'HSK1', 'wǔ', 'ngũ', 'năm, số 5', 'five', 'Hình chữ X có nét ngang'),
(608, 3, '六', 4, 'HSK1', 'liù', 'lục', 'sáu, số 6', 'six', 'Mái nhà nhỏ với 2 chân'),
(609, 3, '七', 2, 'HSK1', 'qī', 'thất', 'bảy, số 7', 'seven', 'Hình chữ T cắt ngang'),
(610, 3, '八', 2, 'HSK1', 'bā', 'bát', 'tám, số 8', 'eight', 'Hai nét tách ra như V ngược'),
(611, 3, '九', 2, 'HSK1', 'jiǔ', 'cửu', 'chín, số 9', 'nine', 'Giống chữ "丸" tròn'),
(612, 3, '十', 2, 'HSK1', 'shí', 'thập', 'mười, số 10', 'ten', 'Nét ngang + nét dọc giao nhau'),
(613, 3, '日', 4, 'HSK1', 'rì', 'nhật', 'mặt trời, ngày', 'sun, day', 'Mặt trời tròn có chấm bên trong'),
(614, 3, '月', 4, 'HSK1', 'yuè', 'nguyệt', 'mặt trăng, tháng', 'moon, month', 'Mặt trăng khuyết'),
(615, 3, '年', 6, 'HSK1', 'nián', 'niên', 'năm', 'year', 'Cái cọc gắn với mùa thu hoạch'),
(616, 3, '我', 7, 'HSK1', 'wǒ', 'ngã', 'tôi', 'I, me', 'Cây giáo (戈) bảo vệ bản thân'),
(617, 3, '你', 7, 'HSK1', 'nǐ', 'nhĩ', 'bạn, anh/chị', 'you', 'Người (亻) + nhỏ (尔)'),
(618, 3, '他', 5, 'HSK1', 'tā', 'tha', 'anh ấy', 'he', 'Người (亻) + cũng (也)'),
(619, 3, '她', 6, 'HSK1', 'tā', 'tha', 'cô ấy', 'she', 'Nữ (女) + cũng (也)'),
(620, 3, '们', 5, 'HSK1', 'men', 'môn', 'những (số nhiều)', 'plural marker', 'Người (亻) + cửa (门)'),
(621, 3, '是', 9, 'HSK1', 'shì', 'thị', 'là, đúng', 'to be', 'Mặt trời (日) trên đúng (正)'),
(622, 3, '不', 4, 'HSK1', 'bù', 'bất', 'không', 'not', 'Phủ định, không phải'),
(623, 3, '没', 7, 'HSK1', 'méi', 'một', 'không có', 'not have', 'Nước (氵) + chìm xuống'),
(624, 3, '有', 6, 'HSK1', 'yǒu', 'hữu', 'có', 'to have', 'Tay (ナ) cầm thịt (月)'),
(625, 3, '在', 6, 'HSK1', 'zài', 'tại', 'ở, đang', 'at, in', 'Đang ở một nơi nào đó'),
(626, 3, '好', 6, 'HSK1', 'hǎo', 'hảo', 'tốt, hay', 'good', 'Nữ (女) + tử (子) = mẹ và con = tốt'),
(627, 3, '吗', 6, 'HSK1', 'ma', 'mã', '(trợ từ nghi vấn)', 'question particle', 'Khẩu (口) + ngựa (马)'),
(628, 3, '呢', 8, 'HSK1', 'ne', 'ni', '(trợ từ)', 'particle', 'Khẩu (口) + ni (尼)'),
(629, 3, '了', 2, 'HSK1', 'le', 'liễu', '(trợ từ hoàn thành)', 'completion particle', 'Hai nét đơn giản'),
(630, 3, '的', 8, 'HSK1', 'de', 'đích', '(của, sở hữu)', 'possessive', 'Trắng (白) + ngọn lửa nhỏ'),
(631, 3, '会', 6, 'HSK1', 'huì', 'hội', 'biết, có thể', 'can, will', 'Hình chữ A với nét ngang'),
(632, 3, '能', 10, 'HSK1', 'néng', 'năng', 'có thể', 'can, able to', 'Hình con gấu mạnh mẽ'),
(633, 3, '想', 13, 'HSK1', 'xiǎng', 'tưởng', 'muốn, nghĩ', 'want, think', 'Tâm (心) + tướng (相)'),
(634, 3, '要', 9, 'HSK1', 'yào', 'yếu', 'muốn, cần', 'want, need', 'Hình người phụ nữ khom lưng'),
(635, 3, '看', 9, 'HSK1', 'kàn', 'khán', 'nhìn, xem', 'to look', 'Tay (手) trên mắt (目) - che mắt nhìn'),
(636, 3, '听', 7, 'HSK1', 'tīng', 'thính', 'nghe', 'to listen', 'Khẩu (口) + cân (斤)'),
(637, 3, '说', 9, 'HSK1', 'shuō', 'thuyết', 'nói', 'to speak', 'Ngôn (讠) + đoài (兑)'),
(638, 3, '读', 10, 'HSK1', 'dú', 'độc', 'đọc', 'to read', 'Ngôn (讠) + bán (卖)'),
(639, 3, '写', 5, 'HSK1', 'xiě', 'tả', 'viết', 'to write', 'Mái nhà + with (与)'),
(640, 3, '吃', 6, 'HSK1', 'chī', 'cật', 'ăn', 'to eat', 'Khẩu (口) + khất (乞)'),
(641, 3, '喝', 12, 'HSK1', 'hē', 'hát', 'uống', 'to drink', 'Khẩu (口) + hát (曷)'),
(642, 3, '去', 5, 'HSK1', 'qù', 'khứ', 'đi', 'to go', 'Đất (土) + khứ'),
(643, 3, '来', 7, 'HSK1', 'lái', 'lai', 'đến', 'to come', 'Hình bông lúa'),
(644, 3, '住', 7, 'HSK1', 'zhù', 'trú', 'ở (cư trú)', 'to live', 'Người (亻) + chủ (主)'),
(645, 3, '叫', 5, 'HSK1', 'jiào', 'khiếu', 'gọi, tên là', 'to call', 'Khẩu (口) + ký (丩)'),
(646, 3, '学', 8, 'HSK1', 'xué', 'học', 'học', 'to study', 'Mái nhà + tử (子)'),
(647, 3, '工', 3, 'HSK1', 'gōng', 'công', 'công việc', 'work', 'Hình chữ I'),
(648, 3, '作', 7, 'HSK1', 'zuò', 'tác', 'làm', 'to do, make', 'Người (亻) + tạc (乍)'),
(649, 3, '家', 10, 'HSK1', 'jiā', 'gia', 'gia đình, nhà', 'home, family', 'Mái nhà + lợn (豕)');

-- HSK 2 Hanzi (50 more characters)
INSERT INTO characters_table (id, language_id, character_text, stroke_count, hsk_level, pinyin, han_viet, meaning_vi, meaning_en, mnemonic_text) VALUES
(650, 3, '知', 8, 'HSK2', 'zhī', 'tri', 'biết', 'to know', 'Mũi tên (矢) + khẩu (口)'),
(651, 3, '道', 12, 'HSK2', 'dào', 'đạo', 'con đường', 'way, road', 'Tiến (辶) + đầu (首)'),
(652, 3, '问', 6, 'HSK2', 'wèn', 'vấn', 'hỏi', 'to ask', 'Cửa (门) + khẩu (口)'),
(653, 3, '题', 15, 'HSK2', 'tí', 'đề', 'đề mục, vấn đề', 'topic, problem', 'Đúng (是) + trang (页)'),
(654, 3, '间', 7, 'HSK2', 'jiān', 'gian', 'khoảng giữa', 'between, room', 'Cửa (门) + nhật (日)'),
(655, 3, '时', 7, 'HSK2', 'shí', 'thời', 'thời gian, lúc', 'time, hour', 'Nhật (日) + thốn (寸)'),
(656, 3, '分', 4, 'HSK2', 'fēn', 'phân', 'phút, chia', 'minute, divide', 'Bát (八) + đao (刀)'),
(657, 3, '现', 8, 'HSK2', 'xiàn', 'hiện', 'hiện tại', 'now', 'Vương (王) + kiến (见)'),
(658, 3, '前', 9, 'HSK2', 'qián', 'tiền', 'phía trước', 'front, before', 'Hình thuyền chèo về trước'),
(659, 3, '后', 6, 'HSK2', 'hòu', 'hậu', 'phía sau', 'back, after', 'Hình ngược lại'),
(660, 3, '上', 3, 'HSK2', 'shàng', 'thượng', 'phía trên', 'up, above', 'Đường thẳng lên trên'),
(661, 3, '下', 3, 'HSK2', 'xià', 'hạ', 'phía dưới', 'down, below', 'Đường thẳng xuống dưới'),
(662, 3, '左', 5, 'HSK2', 'zuǒ', 'tả', 'bên trái', 'left', 'Tay trái cầm dụng cụ'),
(663, 3, '右', 5, 'HSK2', 'yòu', 'hữu', 'bên phải', 'right', 'Tay phải cầm khẩu (口)'),
(664, 3, '里', 7, 'HSK2', 'lǐ', 'lý', 'bên trong', 'inside', 'Ruộng (田) + đất (土)'),
(665, 3, '外', 5, 'HSK2', 'wài', 'ngoại', 'bên ngoài', 'outside', 'Đêm (夕) + xem bói (卜)'),
(666, 3, '中', 4, 'HSK2', 'zhōng', 'trung', 'ở giữa', 'middle', 'Hình mũi tên xuyên qua giữa'),
(667, 3, '国', 8, 'HSK2', 'guó', 'quốc', 'đất nước', 'country', 'Vương (王) trong khung (□)'),
(668, 3, '中国', 12, 'HSK2', 'zhōngguó', 'trung quốc', 'Trung Quốc', 'China', 'Đất nước ở giữa'),
(669, 3, '北京', 13, 'HSK2', 'běijīng', 'bắc kinh', 'Bắc Kinh', 'Beijing', 'Kinh đô phía bắc'),
(670, 3, '汉', 5, 'HSK2', 'hàn', 'hán', 'Hán (dân tộc)', 'Han (Chinese)', 'Nước (氵) + cây (又)'),
(671, 3, '语', 9, 'HSK2', 'yǔ', 'ngữ', 'ngôn ngữ', 'language', 'Ngôn (讠) + ngô (吾)'),
(672, 3, '英', 8, 'HSK2', 'yīng', 'anh', 'tài năng, Anh', 'hero, England', 'Cỏ (艹) + trung tâm (央)'),
(673, 3, '文', 4, 'HSK2', 'wén', 'văn', 'văn, văn tự', 'text, language', 'Hình chữ thập có nét'),
(674, 3, '字', 6, 'HSK2', 'zì', 'tự', 'chữ', 'character', 'Mái nhà + tử (子)'),
(675, 3, '名', 6, 'HSK2', 'míng', 'danh', 'tên', 'name', 'Đêm (夕) + khẩu (口)'),
(676, 3, '字母', 10, 'HSK2', 'zìmǔ', 'tự mẫu', 'chữ cái', 'letter, alphabet', 'Tự + mẫu (mẹ)'),
(677, 3, '书', 4, 'HSK2', 'shū', 'thư', 'sách', 'book', 'Hình tay cầm cây bút'),
(678, 3, '本', 5, 'HSK2', 'běn', 'bản', 'gốc, lượng từ cho sách', 'root, book counter', 'Mộc (木) + nét ngang'),
(679, 3, '页', 6, 'HSK2', 'yè', 'diệp', 'trang giấy', 'page', 'Hình mặt người'),
(680, 3, '块', 7, 'HSK2', 'kuài', 'khối', 'cục, đồng (tiền)', 'piece, dollar', 'Đất (土) + quyết (夬)'),
(681, 3, '钱', 10, 'HSK2', 'qián', 'tiền', 'tiền', 'money', 'Kim (钅) + tàn (戋)'),
(682, 3, '元', 4, 'HSK2', 'yuán', 'nguyên', 'đồng (tiền), nguyên', 'yuan, primary', 'Hai (二) + nhi (儿)'),
(683, 3, '角', 7, 'HSK2', 'jiǎo', 'giác', 'góc, hào', 'corner, dime', 'Hình sừng động vật'),
(684, 3, '毛', 4, 'HSK2', 'máo', 'mao', 'lông, hào', 'hair, dime', 'Hình sợi lông'),
(685, 3, '多', 6, 'HSK2', 'duō', 'đa', 'nhiều', 'many, much', 'Đêm (夕) + đêm (夕) = nhiều đêm'),
(686, 3, '少', 4, 'HSK2', 'shǎo', 'thiểu', 'ít', 'few, little', 'Tiểu (小) + nét gạch'),
(687, 3, '点', 9, 'HSK2', 'diǎn', 'điểm', 'điểm, giờ', 'dot, o''clock', 'Hỏa (灬) bên dưới'),
(688, 3, '半', 5, 'HSK2', 'bàn', 'bán', 'một nửa', 'half', 'Hình chia đôi'),
(689, 3, '万', 3, 'HSK2', 'wàn', 'vạn', 'vạn (10,000)', 'ten thousand', 'Hình người trải rộng'),
(690, 3, '百', 6, 'HSK2', 'bǎi', 'bách', 'trăm', 'hundred', 'Một (一) + bạch (白)'),
(691, 3, '千', 3, 'HSK2', 'qiān', 'thiên', 'nghìn', 'thousand', 'Mười (十) + người (人)'),
(692, 3, '号', 5, 'HSK2', 'hào', 'hiệu', 'số, ngày', 'number, date', 'Khẩu (口) + cây (亏)'),
(693, 3, '次', 6, 'HSK2', 'cì', 'thứ', 'lần (lượng từ)', 'time, occurrence', 'Băng (冫) + khiếm (欠)'),
(694, 3, '岁', 6, 'HSK2', 'suì', 'tuế', 'tuổi', 'year of age', 'Sơn (山) + tịch (夕)'),
(695, 3, '生', 5, 'HSK2', 'shēng', 'sinh', 'sinh ra, sống', 'born, raw', 'Cây con mọc lên từ đất'),
(696, 3, '日', 4, 'HSK2', 'rì', 'nhật', 'ngày', 'day', 'Mặt trời'),
(697, 3, '星', 9, 'HSK2', 'xīng', 'tinh', 'sao', 'star', 'Nhật (日) + sinh (生)'),
(698, 3, '期', 12, 'HSK2', 'qī', 'kỳ', 'kỳ hạn', 'period', 'Kỳ + nguyệt (月)'),
(699, 3, '今', 4, 'HSK2', 'jīn', 'kim', 'hôm nay, hiện tại', 'today, now', 'Mái nhà che');

-- HSK 3 Hanzi (additional 30 chars)
INSERT INTO characters_table (id, language_id, character_text, stroke_count, hsk_level, pinyin, han_viet, meaning_vi, meaning_en) VALUES
(700, 3, '爱', 10, 'HSK3', 'ài', 'ái', 'yêu', 'love'),
(701, 3, '帮', 9, 'HSK3', 'bāng', 'bang', 'giúp đỡ', 'to help'),
(702, 3, '便', 9, 'HSK3', 'biàn', 'tiện', 'tiện lợi', 'convenient'),
(703, 3, '别', 7, 'HSK3', 'bié', 'biệt', 'khác, đừng', 'other, don''t'),
(704, 3, '差', 9, 'HSK3', 'chà', 'sai', 'kém, thiếu', 'lacking, poor'),
(705, 3, '场', 6, 'HSK3', 'chǎng', 'trường', 'sân, nơi', 'place, field'),
(706, 3, '迟', 7, 'HSK3', 'chí', 'trì', 'muộn', 'late'),
(707, 3, '出', 5, 'HSK3', 'chū', 'xuất', 'ra, đi ra', 'to go out'),
(708, 3, '春', 9, 'HSK3', 'chūn', 'xuân', 'mùa xuân', 'spring'),
(709, 3, '词', 7, 'HSK3', 'cí', 'từ', 'từ ngữ', 'word'),
(710, 3, '聪', 15, 'HSK3', 'cōng', 'thông', 'thông minh', 'clever'),
(711, 3, '打', 5, 'HSK3', 'dǎ', 'đả', 'đánh, gọi', 'hit, make call'),
(712, 3, '担', 8, 'HSK3', 'dān', 'đảm', 'gánh, lo', 'carry, worry'),
(713, 3, '蛋', 11, 'HSK3', 'dàn', 'đản', 'trứng', 'egg'),
(714, 3, '当', 6, 'HSK3', 'dāng', 'đương', 'đang, làm', 'while, to act as'),
(715, 3, '到', 8, 'HSK3', 'dào', 'đáo', 'đến', 'to arrive'),
(716, 3, '得', 11, 'HSK3', 'dé/de', 'đắc', 'được, đạt', 'to obtain'),
(717, 3, '灯', 6, 'HSK3', 'dēng', 'đăng', 'đèn', 'lamp'),
(718, 3, '等', 12, 'HSK3', 'děng', 'đẳng', 'chờ đợi', 'to wait'),
(719, 3, '低', 7, 'HSK3', 'dī', 'đê', 'thấp', 'low'),
(720, 3, '弟', 7, 'HSK3', 'dì', 'đệ', 'em trai', 'younger brother'),
(721, 3, '电', 5, 'HSK3', 'diàn', 'điện', 'điện', 'electricity'),
(722, 3, '冬', 5, 'HSK3', 'dōng', 'đông', 'mùa đông', 'winter'),
(723, 3, '懂', 15, 'HSK3', 'dǒng', 'đổng', 'hiểu', 'to understand'),
(724, 3, '动', 6, 'HSK3', 'dòng', 'động', 'di chuyển', 'to move'),
(725, 3, '都', 10, 'HSK3', 'dōu', 'đô', 'tất cả, đều', 'all, both'),
(726, 3, '短', 12, 'HSK3', 'duǎn', 'đoản', 'ngắn', 'short'),
(727, 3, '段', 9, 'HSK3', 'duàn', 'đoạn', 'đoạn', 'section'),
(728, 3, '锻', 14, 'HSK3', 'duàn', 'đoàn', 'rèn luyện', 'to forge, exercise'),
(729, 3, '对', 5, 'HSK3', 'duì', 'đối', 'đúng, đối với', 'right, towards'),
(730, 3, '饿', 10, 'HSK3', 'è', 'ngạ', 'đói', 'hungry');
