#!/usr/bin/env bash
# =============================================================================
# scripts/import_kanjivg.sh
#
# UPGRADE-05: Bulk-import the full KanjiVG dataset (~6500 Kanji) into the
# `characters_table.stroke_order_json` column.
#
# KanjiVG (https://kanjivg.tagaini.net/) ships per-character SVG files like:
#   kanji/06f22.svg   (= 漢, U+6F22)
#   kanji/04eba.svg   (= 人, U+4EBA)
#
# Each SVG contains a <g id="..."> hierarchy with one <path d="..."> per stroke
# in writing order. This script extracts those `d` attributes, packs them into
# a JSON array, and emits an `UPDATE characters_table SET stroke_order_json=...`
# SQL line per character.
#
# Usage:
#   1) Download KanjiVG release:
#        curl -L -o /tmp/kanjivg.zip https://github.com/KanjiVG/kanjivg/releases/latest/download/kanjivg-20220427-main.zip
#        unzip /tmp/kanjivg.zip -d /tmp/kanjivg
#
#   2) Run the importer:
#        ./scripts/import_kanjivg.sh /tmp/kanjivg/kanji > V21__seed_kanjivg_full.sql
#
#   3) Apply the migration:
#        mysql -u $DB_USER -p $DB_PASS lingua_db < V21__seed_kanjivg_full.sql
#
# Requirements: bash, python3, awk
# License: KanjiVG data is CC-BY-SA 3.0 (compatible with this project).
# =============================================================================
set -euo pipefail

KANJIVG_DIR="${1:-}"
if [[ -z "$KANJIVG_DIR" || ! -d "$KANJIVG_DIR" ]]; then
  echo "Usage: $0 <path-to-unzipped-kanjivg/kanji>" >&2
  exit 1
fi

cat <<'HEADER'
-- =====================================================================
-- AUTO-GENERATED by scripts/import_kanjivg.sh
-- KanjiVG full stroke-order import (CC-BY-SA 3.0)
-- =====================================================================
SET autocommit = 0;
START TRANSACTION;

HEADER

count=0
for svg in "$KANJIVG_DIR"/*.svg; do
  base="$(basename "$svg" .svg)"
  # Filter out variant files like "06f22-Kaisho.svg" — keep only the base codepoint.
  [[ "$base" =~ ^[0-9a-f]+$ ]] || continue
  # Convert hex codepoint to actual character.
  char=$(python3 -c "import sys; print(chr(int(sys.argv[1], 16)), end='')" "$base")
  # Extract every path-d attribute, in document order, into a JSON array.
  json=$(python3 - "$svg" <<'PY'
import sys, re, json
with open(sys.argv[1], 'r', encoding='utf-8') as f:
    content = f.read()
strokes = re.findall(r'<path[^>]*\bd="([^"]+)"', content)
print(json.dumps(strokes, ensure_ascii=False))
PY
  )
  # Escape single quotes for SQL.
  esc_char="${char//\'/\'\'}"
  esc_json="${json//\'/\'\'}"
  printf "UPDATE characters_table SET stroke_order_json = '%s' WHERE character_text = '%s';\n" \
    "$esc_json" "$esc_char"
  count=$((count + 1))
done

cat <<'FOOTER'

COMMIT;
SET autocommit = 1;
FOOTER

echo "-- Imported $count characters." >&2
